// Generated by scripts/geocode-places.ts and scripts/geocode-overpass.ts - do not edit by hand.
// Coordinates come from OpenStreetMap (Nominatim / Overpass) and were validated
// against their area. Missing ids keep the area-anchor pin with an honest
// demo-estimate confidence label in the factory.
export type GeocodedPlace = { id: string; coordinates: [number, number]; match: string };

export const geocodedPlaces: GeocodedPlace[] = [
  {
    "id": "little-world-mall",
    "coordinates": [
      73.0664209,
      19.0306438
    ],
    "match": "Little World Mall, Sector 2"
  },
  {
    "id": "kharghar-hills-trek",
    "coordinates": [
      73.0613956,
      19.0725644
    ],
    "match": "Khargar Hills Viewpoint Trail, Owe Camp"
  },
  {
    "id": "kharghar-waterfall-monsoon-hike",
    "coordinates": [
      73.0537143,
      19.0329535
    ],
    "match": "Kharghar Waterfalls, Panvel"
  },
  {
    "id": "kharghar-hills-sunrise-hike",
    "coordinates": [
      73.0613956,
      19.0725644
    ],
    "match": "Khargar Hills Viewpoint Trail, Owe Camp"
  },
  {
    "id": "kyani-co",
    "coordinates": [
      72.8287886,
      18.9441069
    ],
    "match": "Kyani & Co., 657"
  },
  {
    "id": "britannia-co",
    "coordinates": [
      72.8403579,
      18.9344727
    ],
    "match": "Britannia & Co. Restaurant, 11"
  },
  {
    "id": "yazdani-bakery",
    "coordinates": [
      72.8336019,
      18.9331806
    ],
    "match": "Yazdani Bakery, Cawasji Patel Street"
  },
  {
    "id": "cafe-military",
    "coordinates": [
      72.8320601,
      18.9307521
    ],
    "match": "Cafe Military, Mupanna P Shetty Marg"
  },
  {
    "id": "ideal-corner",
    "coordinates": [
      72.8342167,
      18.9349624
    ],
    "match": "Ideal Corner, Bomanji Lane"
  },
  {
    "id": "khyber",
    "coordinates": [
      72.8316572,
      18.9283232
    ],
    "match": "Khyber, Kaikhushru Dubash Marg"
  },
  {
    "id": "trishna",
    "coordinates": [
      72.8323932,
      18.9286576
    ],
    "match": "Trishna, Rope Walk Street"
  },
  {
    "id": "gokul",
    "coordinates": [
      72.8322377,
      18.9231106
    ],
    "match": "Gokul Bar & Wine shop, Tullock Road"
  },
  {
    "id": "leopold-cafe",
    "coordinates": [
      72.831763,
      18.9227115
    ],
    "match": "Cafe Leopold, Nowroji Ferdonji Street"
  },
  {
    "id": "cafe-mondegar",
    "coordinates": [
      72.8321786,
      18.9240421
    ],
    "match": "Cafe Mondegar, Chhatrapati Shivaji Maharaj Road"
  },
  {
    "id": "bademiya-kebab-stall",
    "coordinates": [
      72.8325111,
      18.9231497
    ],
    "match": "Bademiya Seekh Kebab Stall, Tullock Road"
  },
  {
    "id": "theobroma-colaba",
    "coordinates": [
      72.8292274,
      18.9192171
    ],
    "match": "Theobroma, Nanabhai Moos Marg (Upper Colaba Road)"
  },
  {
    "id": "cafe-churchill",
    "coordinates": [
      72.8302321,
      18.919922
    ],
    "match": "Cafe Churchill, Nanabhai Moos Marg (Upper Colaba Road)"
  },
  {
    "id": "woodside-inn",
    "coordinates": [
      72.8318781,
      18.9249021
    ],
    "match": "Woodside Inn, Nathalal M. Parikh Road"
  },
  {
    "id": "cream-centre",
    "coordinates": [
      72.8133136,
      18.955594
    ],
    "match": "Cream Centre, Marine Drive"
  },
  {
    "id": "noor-mohammadi-hotel",
    "coordinates": [
      72.8322448,
      18.9578129
    ],
    "match": "Noor Mohammadi Hotel, J.J. Flyover"
  },
  {
    "id": "tawakkal-sweets",
    "coordinates": [
      72.8309033,
      18.9600922
    ],
    "match": "Tawakkal sweets, Sayed Lane (Khara Tank Street)"
  },
  {
    "id": "candies",
    "coordinates": [
      72.8298692,
      19.0495544
    ],
    "match": "Candies, Nityanand Street"
  },
  {
    "id": "hearsch-bakery",
    "coordinates": [
      72.8269905,
      19.0551689
    ],
    "match": "J Hearsch and Co, Hill Road"
  },
  {
    "id": "pali-bhavan",
    "coordinates": [
      72.8294205,
      19.0620905
    ],
    "match": "Pali Bhavan, Dr. BR Ambedkar Road"
  },
  {
    "id": "the-bagel-shop",
    "coordinates": [
      72.8248491,
      19.0631425
    ],
    "match": "The Bagel Shop, 30"
  },
  {
    "id": "jai-jawan",
    "coordinates": [
      72.8346675,
      19.0642496
    ],
    "match": "Jai Jawan, RK Patkar Marg (Waterfield Road)"
  },
  {
    "id": "carter-road-khau-galli",
    "coordinates": [
      72.822656,
      19.0705997
    ],
    "match": "Carter Road Social, Khau Galli"
  },
  {
    "id": "yoko-sizzlers",
    "coordinates": [
      72.83473,
      19.0562679
    ],
    "match": "Yoko Sizzlers, Hill Road"
  },
  {
    "id": "amar-juice-centre",
    "coordinates": [
      72.836922,
      19.1093895
    ],
    "match": "Amar Juice Centre, East West road No 3"
  },
  {
    "id": "versova-beach-cafes",
    "coordinates": [
      72.8288816,
      19.1365431
    ],
    "match": "Silver Beach Cafe, Pramod Navalkar Road"
  },
  {
    "id": "aaswad",
    "coordinates": [
      72.8405857,
      19.0256504
    ],
    "match": "Aaswad, Lady Jamshedji Road"
  },
  {
    "id": "cafe-madras",
    "coordinates": [
      72.8550473,
      19.0276726
    ],
    "match": "Cafe Madras, Bhau Daji Road"
  },
  {
    "id": "cafe-mysore",
    "coordinates": [
      72.8554829,
      19.0275709
    ],
    "match": "Cafe Mysore, King's Circle"
  },
  {
    "id": "slink-bardot",
    "coordinates": [
      72.8175515,
      19.0169864
    ],
    "match": "Slink & Bardot, 329/A"
  },
  {
    "id": "tote-on-the-turf",
    "coordinates": [
      72.8232049,
      18.9819716
    ],
    "match": "Tote on the Turf, Shantinagar"
  },
  {
    "id": "bandra-west-bar-street",
    "coordinates": [
      72.8258171,
      19.0546125
    ],
    "match": "Old Street Cafe & Bar, Hill Road"
  },
  {
    "id": "bonobo",
    "coordinates": [
      72.8336758,
      19.0654946
    ],
    "match": "Bonobo, 33rd Road"
  },
  {
    "id": "totos-garage",
    "coordinates": [
      72.8298004,
      19.0624858
    ],
    "match": "Toto's Garage, 30"
  },
  {
    "id": "prithvi-theatre-cafe-night",
    "coordinates": [
      72.8257203,
      19.1062094
    ],
    "match": "Prithvi Café, 20"
  },
  {
    "id": "indigo-colaba",
    "coordinates": [
      72.8320651,
      18.9222725
    ],
    "match": "Indigo, Mandlik Road"
  },
  {
    "id": "marine-drive-promenade-night-walk",
    "coordinates": [
      72.821601,
      18.9295883
    ],
    "match": "Marine Drive Promenade, Nariman Point"
  },
  {
    "id": "powai-lakefront-evening-walk",
    "coordinates": [
      72.913808,
      19.129091
    ],
    "match": "Guest House Lakefront, Lakeside Road"
  },
  {
    "id": "crawford-market",
    "coordinates": [
      72.8345108,
      18.9473499
    ],
    "match": "Crawford Market, Fort"
  },
  {
    "id": "mangaldas-market",
    "coordinates": [
      72.8323989,
      18.9482851
    ],
    "match": "Mangaldas Market, Sheikh Memon Street"
  },
  {
    "id": "abdul-rehman-street",
    "coordinates": [
      72.8327484,
      18.950882
    ],
    "match": "Abdul Rehman Street, Khadak"
  },
  {
    "id": "linking-road-shopping-street",
    "coordinates": [
      72.8332947,
      19.0685241
    ],
    "match": "High Street, Linking Road"
  },
  {
    "id": "infiniti-mall-andheri",
    "coordinates": [
      72.8309461,
      19.1412831
    ],
    "match": "Infiniti Mall Andheri, Oshiwara"
  },
  {
    "id": "kala-ghoda-gallery-night-walks",
    "coordinates": [
      72.8325994,
      18.9284581
    ],
    "match": "Kala Ghoda"
  },
  {
    "id": "ballard-estate-evening-strip",
    "coordinates": [
      72.8391325,
      18.9366512
    ],
    "match": "Ballard Estate"
  },
  {
    "id": "chor-bazaar-edge-mutton-street",
    "coordinates": [
      72.829914,
      18.9593519
    ],
    "match": "Chor Bazaar"
  },
  {
    "id": "cn-naik-market",
    "coordinates": [
      72.8295989,
      18.9411989
    ],
    "match": "Naik Bus Stop"
  },
  {
    "id": "azad-maidan-fitness-track",
    "coordinates": [
      72.832942,
      18.9415557
    ],
    "match": "Azad Maidan Police Station"
  },
  {
    "id": "horniman-circle-garden",
    "coordinates": [
      72.8350219,
      18.9319765
    ],
    "match": "Horniman Circle Garden"
  },
  {
    "id": "azad-maidan-lounging",
    "coordinates": [
      72.832942,
      18.9415557
    ],
    "match": "Azad Maidan Police Station"
  },
  {
    "id": "cross-maidan-evening-walk",
    "coordinates": [
      72.8296103,
      18.937434
    ],
    "match": "Cross Maidan"
  },
  {
    "id": "grand-hotel-fort",
    "coordinates": [
      72.8408238,
      18.9361901
    ],
    "match": "Grand Hotel"
  },
  {
    "id": "hotel-marine-plaza",
    "coordinates": [
      72.8230972,
      18.9311659
    ],
    "match": "Hotel Marine Plaza"
  },
  {
    "id": "hotel-harbour-view-fort",
    "coordinates": [
      72.8318466,
      18.9187992
    ],
    "match": "Hotel Harbour View"
  },
  {
    "id": "chhatrapati-shivaji-maharaj-terminus-heritage-walk",
    "coordinates": [
      72.8318464,
      18.9407842
    ],
    "match": "Chhatrapati Shivaji Maharaj Terminus"
  },
  {
    "id": "asiatic-society-steps",
    "coordinates": [
      72.8361416,
      18.9318316
    ],
    "match": "Asiatic Society Town Hall;Asiatic Society Municipal Library"
  },
  {
    "id": "rbi-monetary-museum",
    "coordinates": [
      72.8361829,
      18.934005
    ],
    "match": "RBI Monetary Museum"
  },
  {
    "id": "st-thomas-cathedral",
    "coordinates": [
      72.8336828,
      18.9318595
    ],
    "match": "St Thomas Cathedral"
  },
  {
    "id": "elphinstone-college-facade-walk",
    "coordinates": [
      72.8302832,
      18.9434192
    ],
    "match": "Elphinstone Technical High School and Junior College Mumbai"
  },
  {
    "id": "david-sassoon-library-extension-visit",
    "coordinates": [
      72.8311551,
      18.9276912
    ],
    "match": "Sir David Sassoon Library"
  },
  {
    "id": "horniman-circle-heritage-loop",
    "coordinates": [
      72.8342863,
      18.9321217
    ],
    "match": "Horniman Circle"
  },
  {
    "id": "bombay-samachar-building-walk",
    "coordinates": [
      72.8339592,
      18.9298205
    ],
    "match": "Bombay Samachar Marg"
  },
  {
    "id": "gateway-of-india-heritage-hour",
    "coordinates": [
      72.8345228,
      18.9229191
    ],
    "match": "Gateway of India - Mandwa Rewas Ferry Terminal"
  },
  {
    "id": "regal-cinema-art-deco-visit",
    "coordinates": [
      72.8325192,
      18.9245934
    ],
    "match": "Regal Cinema"
  },
  {
    "id": "fort-art-deco-trail",
    "coordinates": [
      72.8306139,
      18.9293596
    ],
    "match": "विक्टोरिया गोथिक और आर्ट डेका इन्सेंबल्स ऑफ़ मुंबई"
  },
  {
    "id": "municipal-corporation-building-view-stop",
    "coordinates": [
      72.8342181,
      18.940677
    ],
    "match": "Municipal Corporation of Greater Mumbai"
  },
  {
    "id": "kala-ghoda-gallery-evening",
    "coordinates": [
      72.8325994,
      18.9284581
    ],
    "match": "Kala Ghoda"
  },
  {
    "id": "jehangir-art-gallery-visit",
    "coordinates": [
      72.8317177,
      18.9272846
    ],
    "match": "Jehangir Art Gallery"
  },
  {
    "id": "horniman-circle-canopy-hour",
    "coordinates": [
      72.8342863,
      18.9321217
    ],
    "match": "Horniman Circle"
  },
  {
    "id": "cross-maidan-green-hour",
    "coordinates": [
      72.8296103,
      18.937434
    ],
    "match": "Cross Maidan"
  },
  {
    "id": "azad-maidan-morning-green-loop",
    "coordinates": [
      72.832942,
      18.9415557
    ],
    "match": "Azad Maidan Police Station"
  },
  {
    "id": "cooperage-garden-shade-walk",
    "coordinates": [
      72.8288833,
      18.9257208
    ],
    "match": "Cooperage Garden"
  },
  {
    "id": "kala-ghoda-sketch-walk-workshop",
    "coordinates": [
      72.8325994,
      18.9284581
    ],
    "match": "Kala Ghoda"
  },
  {
    "id": "kala-ghoda-photography-walk-class",
    "coordinates": [
      72.8325994,
      18.9284581
    ],
    "match": "Kala Ghoda"
  },
  {
    "id": "horniman-circle-family-picnic",
    "coordinates": [
      72.8342863,
      18.9321217
    ],
    "match": "Horniman Circle"
  },
  {
    "id": "horniman-circle-family-play-slot",
    "coordinates": [
      72.8342863,
      18.9321217
    ],
    "match": "Horniman Circle"
  },
  {
    "id": "baghdadi",
    "coordinates": [
      72.8324423,
      18.9229102
    ],
    "match": "बगदादी रेस्टोरेंट"
  },
  {
    "id": "geoffreys-at-marine-plaza",
    "coordinates": [
      72.8230972,
      18.9311659
    ],
    "match": "Hotel Marine Plaza"
  },
  {
    "id": "cafe-mondegar-night-jukebox",
    "coordinates": [
      72.8321786,
      18.9240421
    ],
    "match": "Cafe Mondegar"
  },
  {
    "id": "woodside-inn-night-strip",
    "coordinates": [
      72.8318781,
      18.9249021
    ],
    "match": "Woodside Inn"
  },
  {
    "id": "army-navy-store",
    "coordinates": [
      72.8309256,
      18.9279857
    ],
    "match": "Army And Navy Building"
  },
  {
    "id": "gateway-of-india-speedboat-ride",
    "coordinates": [
      72.8345228,
      18.9229191
    ],
    "match": "Gateway of India - Mandwa Rewas Ferry Terminal"
  },
  {
    "id": "gateway-of-india-jet-ski-slot",
    "coordinates": [
      72.8345228,
      18.9229191
    ],
    "match": "Gateway of India - Mandwa Rewas Ferry Terminal"
  },
  {
    "id": "the-taj-mahal-palace",
    "coordinates": [
      72.8330507,
      18.921902
    ],
    "match": "Taj Mahal Palace"
  },
  {
    "id": "the-oberoi-mumbai",
    "coordinates": [
      72.8324577,
      18.9284247
    ],
    "match": "Renu Oberoi"
  },
  {
    "id": "trident-nariman-point",
    "coordinates": [
      72.8210332,
      18.9276399
    ],
    "match": "Trident, Nariman-Point"
  },
  {
    "id": "hotel-diplomat",
    "coordinates": [
      72.8322344,
      18.9216884
    ],
    "match": "Hotel Diplomat"
  },
  {
    "id": "fariyas-hotel",
    "coordinates": [
      72.8300047,
      18.9170456
    ],
    "match": "Fariyas Hotel Mumbai"
  },
  {
    "id": "colaba-backpacker-hostels-row",
    "coordinates": [
      72.8306735,
      18.9199659
    ],
    "match": "Backpacker Panda Colaba"
  },
  {
    "id": "hotel-suba-palace",
    "coordinates": [
      72.8329689,
      18.9240096
    ],
    "match": "Hotel Suba Palace"
  },
  {
    "id": "gateway-of-india-morning-walk",
    "coordinates": [
      72.8345228,
      18.9229191
    ],
    "match": "Gateway of India - Mandwa Rewas Ferry Terminal"
  },
  {
    "id": "prince-of-wales-museum-courtyard",
    "coordinates": [
      72.8314401,
      18.9187398
    ],
    "match": "Prince Court"
  },
  {
    "id": "colaba-art-gallery-row",
    "coordinates": [
      72.8313854,
      18.9258376
    ],
    "match": "नॅशनल गॅलरी ऑफ मॉडर्न आर्ट"
  },
  {
    "id": "sassoon-docks-early-morning-walk",
    "coordinates": [
      72.8252993,
      18.9110357
    ],
    "match": "Sassoon Docks"
  },
  {
    "id": "dhanraj-mahal-art-deco-walk",
    "coordinates": [
      72.8306139,
      18.9293596
    ],
    "match": "विक्टोरिया गोथिक और आर्ट डेका इन्सेंबल्स ऑफ़ मुंबई"
  },
  {
    "id": "afghan-church-heritage-visit",
    "coordinates": [
      72.8167686,
      18.9067788
    ],
    "match": "Afghan Church"
  },
  {
    "id": "sachivalaya-gymkhana-heritage-walk",
    "coordinates": [
      72.8265236,
      18.9259525
    ],
    "match": "Sachivalay Gymkhana"
  },
  {
    "id": "sassoon-docks-waterfront-walk",
    "coordinates": [
      72.8252993,
      18.9110357
    ],
    "match": "Sassoon Docks"
  },
  {
    "id": "colaba-woods-neighborhood-lanes",
    "coordinates": [
      72.81909,
      18.9133491
    ],
    "match": "Colaba Woods Garden"
  },
  {
    "id": "colaba-terrarium-building-class",
    "coordinates": [
      72.8272192,
      18.9154815
    ],
    "match": "Colaba Court Building"
  },
  {
    "id": "colaba-family-garden-picnic",
    "coordinates": [
      72.81909,
      18.9133491
    ],
    "match": "Colaba Woods Garden"
  },
  {
    "id": "marine-drive-promenade-chai-carts",
    "coordinates": [
      72.8208,
      18.9296046
    ],
    "match": "Marine Drive Promenade"
  },
  {
    "id": "oberoi-bar-nariman-point",
    "coordinates": [
      72.8235859,
      18.927089
    ],
    "match": "Nariman Point"
  },
  {
    "id": "trident-nariman-point-bar",
    "coordinates": [
      72.8210332,
      18.9276399
    ],
    "match": "Trident, Nariman-Point"
  },
  {
    "id": "nariman-point-seafront-evening",
    "coordinates": [
      72.8235859,
      18.927089
    ],
    "match": "Nariman Point"
  },
  {
    "id": "pizza-by-the-bay-night-counter",
    "coordinates": [
      72.8238813,
      18.9332945
    ],
    "match": "Pizza By The Bay"
  },
  {
    "id": "marine-drive-badminton-on-promenade-meetup",
    "coordinates": [
      72.8208,
      18.9296046
    ],
    "match": "Marine Drive Promenade"
  },
  {
    "id": "nariman-point-sunrise-run",
    "coordinates": [
      72.8235859,
      18.927089
    ],
    "match": "Nariman Point"
  },
  {
    "id": "marine-drive-promenade-run-loop",
    "coordinates": [
      72.8208,
      18.9296046
    ],
    "match": "Marine Drive Promenade"
  },
  {
    "id": "marine-drive-promenade-sit-outs",
    "coordinates": [
      72.8208,
      18.9296046
    ],
    "match": "Marine Drive Promenade"
  },
  {
    "id": "chowpatty-garden-lounging",
    "coordinates": [
      72.8076111,
      18.9555432
    ],
    "match": "Kilachand Garden (Chowpatty Bandstand)"
  },
  {
    "id": "kamala-nehru-park-visit",
    "coordinates": [
      72.8046207,
      18.955096
    ],
    "match": "Kamala Nehru Park"
  },
  {
    "id": "hanging-gardens-visit",
    "coordinates": [
      72.8048197,
      18.9566065
    ],
    "match": "Pherozeshah Mehta Gardens (Hanging Gardens)"
  },
  {
    "id": "priyadarshini-park-ground",
    "coordinates": [
      72.7995926,
      18.9569155
    ],
    "match": "Priyadarshani Park / Shimla House"
  },
  {
    "id": "nariman-point-sunset-point",
    "coordinates": [
      72.8235859,
      18.927089
    ],
    "match": "Nariman Point"
  },
  {
    "id": "marine-plaza-promenade-stay",
    "coordinates": [
      72.8230972,
      18.9311659
    ],
    "match": "Hotel Marine Plaza"
  },
  {
    "id": "intercontinental-marine-drive",
    "coordinates": [
      72.8243065,
      18.9349915
    ],
    "match": "InterContinental Marine Drive, Mumbai"
  },
  {
    "id": "sea-green-hotel",
    "coordinates": [
      72.8237555,
      18.9326798
    ],
    "match": "Sea Green Hotel"
  },
  {
    "id": "nariman-point-business-hotels",
    "coordinates": [
      72.8235859,
      18.927089
    ],
    "match": "Nariman Point"
  },
  {
    "id": "art-deco-marine-drive-walk",
    "coordinates": [
      72.8306139,
      18.9293596
    ],
    "match": "विक्टोरिया गोथिक और आर्ट डेका इन्सेंबल्स ऑफ़ मुंबई"
  },
  {
    "id": "eros-cinema-facade-visit",
    "coordinates": [
      72.8279388,
      18.9322385
    ],
    "match": "Eros Cinema"
  },
  {
    "id": "taraporewala-aquarium-precinct-walk",
    "coordinates": [
      72.8199216,
      18.9491882
    ],
    "match": "Taraporewala Aquarium"
  },
  {
    "id": "chowpatty-sand-garden-edge",
    "coordinates": [
      72.8076111,
      18.9555432
    ],
    "match": "Kilachand Garden (Chowpatty Bandstand)"
  },
  {
    "id": "art-deco-photography-walk-class",
    "coordinates": [
      72.8306139,
      18.9293596
    ],
    "match": "विक्टोरिया गोथिक और आर्ट डेका इन्सेंबल्स ऑफ़ मुंबई"
  },
  {
    "id": "chowpatty-family-beach-evening",
    "coordinates": [
      72.8114236,
      18.9543869
    ],
    "match": "Girgaum Chowpatty Beach"
  },
  {
    "id": "jaffer-bhais-delhi-darbar",
    "coordinates": [
      72.823385,
      18.9614573
    ],
    "match": "Delhi Darbar"
  },
  {
    "id": "mohammad-ali-road-kebab-stretch",
    "coordinates": [
      72.8343785,
      18.9518717
    ],
    "match": "Muhammad Ali Road"
  },
  {
    "id": "bhendi-bazaar-iftar-stalls",
    "coordinates": [
      72.8317816,
      18.9579427
    ],
    "match": "Bhendi Bazaar"
  },
  {
    "id": "mohammad-ali-road-night-kebab-stretch",
    "coordinates": [
      72.8343785,
      18.9518717
    ],
    "match": "Muhammad Ali Road"
  },
  {
    "id": "bhendi-bazaar-iftar-night-stalls",
    "coordinates": [
      72.8317816,
      18.9579427
    ],
    "match": "Bhendi Bazaar"
  },
  {
    "id": "noor-mohammadi-late-counter",
    "coordinates": [
      72.8322448,
      18.9578129
    ],
    "match": "Noor Mohammadi Hotel"
  },
  {
    "id": "bhendi-bazaar-antique-lanes",
    "coordinates": [
      72.8317816,
      18.9579427
    ],
    "match": "Bhendi Bazaar"
  },
  {
    "id": "chor-bazaar-mutton-street",
    "coordinates": [
      72.829914,
      18.9593519
    ],
    "match": "Chor Bazaar"
  },
  {
    "id": "bhendi-bazaar-perfume-shops",
    "coordinates": [
      72.8317816,
      18.9579427
    ],
    "match": "Bhendi Bazaar"
  },
  {
    "id": "minara-masjid-shopping-stretch",
    "coordinates": [
      72.8330818,
      18.95452
    ],
    "match": "Minara Masjid"
  },
  {
    "id": "bhendi-bazaar-heritage-lodges",
    "coordinates": [
      72.8317816,
      18.9579427
    ],
    "match": "Bhendi Bazaar"
  },
  {
    "id": "mohammad-ali-road-budget-stays",
    "coordinates": [
      72.8343785,
      18.9518717
    ],
    "match": "Muhammad Ali Road"
  },
  {
    "id": "marine-lines-edge-guesthouses",
    "coordinates": [
      72.8230857,
      18.9465849
    ],
    "match": "Marine Lines"
  },
  {
    "id": "bhendi-bazaar-heritage-food-and-faith-walk",
    "coordinates": [
      72.8317816,
      18.9579427
    ],
    "match": "Bhendi Bazaar"
  },
  {
    "id": "minara-masjid-lane-visit",
    "coordinates": [
      72.8330818,
      18.95452
    ],
    "match": "Minara Masjid"
  },
  {
    "id": "bhendi-bazaar-heritage-market-walk",
    "coordinates": [
      72.8317816,
      18.9579427
    ],
    "match": "Bhendi Bazaar"
  },
  {
    "id": "bhendi-bazaar-calligraphy-class",
    "coordinates": [
      72.8317816,
      18.9579427
    ],
    "match": "Bhendi Bazaar"
  },
  {
    "id": "bhendi-bazaar-family-food-walk",
    "coordinates": [
      72.8317816,
      18.9579427
    ],
    "match": "Bhendi Bazaar"
  },
  {
    "id": "bhendi-bazaar-family-market-stroll",
    "coordinates": [
      72.8317816,
      18.9579427
    ],
    "match": "Bhendi Bazaar"
  },
  {
    "id": "hiranandani-gardens-cafe-strip",
    "coordinates": [
      72.9151649,
      19.1299491
    ],
    "match": "Gulmohar Garden Cafe"
  },
  {
    "id": "powai-plaza-eateries",
    "coordinates": [
      72.9131293,
      19.1229385
    ],
    "match": "Powai Plaza"
  },
  {
    "id": "central-avenue-bakeries",
    "coordinates": [
      72.9124779,
      19.1205304
    ],
    "match": "Central Avenue"
  },
  {
    "id": "powai-plaza-late-eateries",
    "coordinates": [
      72.9131293,
      19.1229385
    ],
    "match": "Powai Plaza"
  },
  {
    "id": "galleria-market",
    "coordinates": [
      72.9112616,
      19.1191177
    ],
    "match": "Galleria Juice and Snacks"
  },
  {
    "id": "central-avenue-shops",
    "coordinates": [
      72.9124779,
      19.1205304
    ],
    "match": "Central Avenue"
  },
  {
    "id": "powai-plaza-retail-strip",
    "coordinates": [
      72.9131293,
      19.1229385
    ],
    "match": "Powai Plaza"
  },
  {
    "id": "powai-lake-kayaking-session",
    "coordinates": [
      72.9059687,
      19.1200084
    ],
    "match": "Powai Lake Station"
  },
  {
    "id": "powai-lake-paddle-boarding",
    "coordinates": [
      72.9059687,
      19.1200084
    ],
    "match": "Powai Lake Station"
  },
  {
    "id": "powai-lake-rowing-course",
    "coordinates": [
      72.9059687,
      19.1200084
    ],
    "match": "Powai Lake Station"
  },
  {
    "id": "powai-vihar-lake-walk",
    "coordinates": [
      72.902287,
      19.1178693
    ],
    "match": "Lake Palace Powai Vihar CHS"
  },
  {
    "id": "iit-powai-trail-edge",
    "coordinates": [
      72.9137395,
      19.1242338
    ],
    "match": "IIT Powai Station"
  },
  {
    "id": "powai-lake-promenade",
    "coordinates": [
      72.9059687,
      19.1200084
    ],
    "match": "Powai Lake Station"
  },
  {
    "id": "hiranandani-gardens-stroll",
    "coordinates": [
      72.911464,
      19.1183882
    ],
    "match": "Hiranandani Gardens"
  },
  {
    "id": "powai-garden-sit-outs",
    "coordinates": [
      72.8948183,
      19.1256563
    ],
    "match": "Dr. Babasaheb Ambedkar Udyan/Powai Gardens"
  },
  {
    "id": "nirvana-park-visit",
    "coordinates": [
      72.9118156,
      19.122422
    ],
    "match": "Nirvana Park"
  },
  {
    "id": "meluha-the-fern-powai",
    "coordinates": [
      72.9109596,
      19.11783
    ],
    "match": "Meluha The Fern"
  },
  {
    "id": "hotel-powai-inn",
    "coordinates": [
      72.8987555,
      19.1346222
    ],
    "match": "Residence Inn Powai"
  },
  {
    "id": "rodas-an-ecotel-hotel",
    "coordinates": [
      72.9116829,
      19.1185925
    ],
    "match": "Rodas - An Ecotel Hotel"
  },
  {
    "id": "iit-bombay-heritage-buildings-walk",
    "coordinates": [
      72.913191,
      19.1357052
    ],
    "match": "small swimming pool"
  },
  {
    "id": "powai-lake-birding-corner",
    "coordinates": [
      72.9059687,
      19.1200084
    ],
    "match": "Powai Lake Station"
  },
  {
    "id": "powai-garden-wetland-strip",
    "coordinates": [
      72.8948183,
      19.1256563
    ],
    "match": "Dr. Babasaheb Ambedkar Udyan/Powai Gardens"
  },
  {
    "id": "iit-bombay-green-trail-edge",
    "coordinates": [
      72.913191,
      19.1357052
    ],
    "match": "small swimming pool"
  },
  {
    "id": "powai-vihar-lakeside-walk-extension",
    "coordinates": [
      72.9029746,
      19.1171079
    ],
    "match": "Powai Vihar Park"
  },
  {
    "id": "powai-park-family-play-slot",
    "coordinates": [
      72.9029746,
      19.1171079
    ],
    "match": "Powai Vihar Park"
  },
  {
    "id": "shivaji-park-chaat-stalls",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "dadar-beach-bhel-stalls",
    "coordinates": [
      72.8302099,
      19.0219216
    ],
    "match": "Dadar Beach"
  },
  {
    "id": "shivaji-park-evening-walk-circuit",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "shivaji-park-sports-shops",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "shivaji-park-running-loop",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "five-gardens-morning-run",
    "coordinates": [
      72.8538406,
      19.0201251
    ],
    "match": "Garden E, Five Gardens"
  },
  {
    "id": "shivaji-park-lounging",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "five-gardens-outing",
    "coordinates": [
      72.8538406,
      19.0201251
    ],
    "match": "Garden E, Five Gardens"
  },
  {
    "id": "dadar-beach-sit-outs",
    "coordinates": [
      72.8302099,
      19.0219216
    ],
    "match": "Dadar Beach"
  },
  {
    "id": "portuguese-church-garden-rest",
    "coordinates": [
      72.8364514,
      19.0186203
    ],
    "match": "Portuguese Church"
  },
  {
    "id": "hotel-central-park-dadar",
    "coordinates": [
      72.8431748,
      19.0172069
    ],
    "match": "Dadar (Central)"
  },
  {
    "id": "matunga-east-guesthouses",
    "coordinates": [
      72.8520846,
      19.0261579
    ],
    "match": "Matunga East"
  },
  {
    "id": "shivaji-park-memorial-circuit",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "dadar-parsi-colony-heritage-walk",
    "coordinates": [
      72.8507293,
      19.0207973
    ],
    "match": "Dadar Parsi Colony Gymkhana"
  },
  {
    "id": "portuguese-church-visit-dadar",
    "coordinates": [
      72.8364514,
      19.0186203
    ],
    "match": "Portuguese Church"
  },
  {
    "id": "shivaji-park-green-loop",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "five-gardens-canopy-walk",
    "coordinates": [
      72.8538406,
      19.0201251
    ],
    "match": "Garden E, Five Gardens"
  },
  {
    "id": "dadar-beach-shoreline-walk",
    "coordinates": [
      72.8302099,
      19.0219216
    ],
    "match": "Dadar Beach"
  },
  {
    "id": "shivaji-park-sea-face-morning-walk",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "dadar-flower-arrangement-class",
    "coordinates": [
      72.8372248,
      19.0117531
    ],
    "match": "Dadar Flower Market"
  },
  {
    "id": "dadar-block-printing-class",
    "coordinates": [
      72.8397018,
      19.0195661
    ],
    "match": "GOREGAOKAR DADAR PREMISES BLOCK B"
  },
  {
    "id": "five-gardens-family-evening",
    "coordinates": [
      72.8538406,
      19.0201251
    ],
    "match": "Garden E, Five Gardens"
  },
  {
    "id": "shivaji-park-family-play-slot",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "dadar-beach-family-evening",
    "coordinates": [
      72.8302099,
      19.0219216
    ],
    "match": "Dadar Beach"
  },
  {
    "id": "dadar-family-chaat-treat-walk",
    "coordinates": [
      72.8387056,
      19.0136767
    ],
    "match": "Dadar Waste Treatment Centre"
  },
  {
    "id": "ram-ashraya",
    "coordinates": [
      72.8517121,
      19.0280158
    ],
    "match": "Ram Ashray South Indian"
  },
  {
    "id": "b-merwan-co",
    "coordinates": [
      72.8394706,
      19.0014915
    ],
    "match": "Aimai Merwanji Street"
  },
  {
    "id": "a-rama-nayaks-udipi-shri-krishna-boarding",
    "coordinates": [
      72.850662,
      19.0273999
    ],
    "match": "A Rama Nayak's Shrikrishna Boarding"
  },
  {
    "id": "kings-circle-chaat-carts",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "kings-circle-night-chaat-carts",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "kings-circle-shopping-strip",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "matunga-east-provision-lanes",
    "coordinates": [
      72.8520846,
      19.0261579
    ],
    "match": "Matunga East"
  },
  {
    "id": "matunga-east-vegetable-market",
    "coordinates": [
      72.8520846,
      19.0261579
    ],
    "match": "Matunga East"
  },
  {
    "id": "king-circle-fitness-walk",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "king-circle-garden",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "matunga-gymkhana-grounds",
    "coordinates": [
      72.8496238,
      19.0253435
    ],
    "match": "Matunga Gymkhana"
  },
  {
    "id": "five-gardens-tai-chi-slot",
    "coordinates": [
      72.8538406,
      19.0201251
    ],
    "match": "Garden E, Five Gardens"
  },
  {
    "id": "king-circle-budget-hotels",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "matunga-gymkhana-green-edge",
    "coordinates": [
      72.8496238,
      19.0253435
    ],
    "match": "Matunga Gymkhana"
  },
  {
    "id": "king-circle-banyan-corner",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "king-circle-family-garden-slot",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "itc-grand-central-dining",
    "coordinates": [
      72.8382792,
      18.9982254
    ],
    "match": "ITC Grand Central"
  },
  {
    "id": "worli-koliwada-seafood-homes",
    "coordinates": [
      72.8173559,
      19.0215609
    ],
    "match": "Worli Koliwada"
  },
  {
    "id": "four-seasons-hotel-bar",
    "coordinates": [
      72.8203935,
      18.994204
    ],
    "match": "Four Seasons Hotel"
  },
  {
    "id": "aer-at-four-seasons",
    "coordinates": [
      72.8203935,
      18.994204
    ],
    "match": "Four Seasons Hotel"
  },
  {
    "id": "lower-parel-design-stores",
    "coordinates": [
      72.8302756,
      18.99568
    ],
    "match": "Lower Parel"
  },
  {
    "id": "worli-sea-face-saturday-market",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "mathuradas-mill-compound-shops",
    "coordinates": [
      72.8466022,
      19.0119707
    ],
    "match": "Kohinoor Mill Compound"
  },
  {
    "id": "lower-parel-mill-run-loop",
    "coordinates": [
      72.8302756,
      18.99568
    ],
    "match": "Lower Parel"
  },
  {
    "id": "mahalaxmi-racecourse-running-loop",
    "coordinates": [
      72.819762,
      18.9851816
    ],
    "match": "Mahalaxmi Racecourse"
  },
  {
    "id": "lower-parel-business-park-gardens",
    "coordinates": [
      72.8301949,
      19.0042547
    ],
    "match": "BMC Pay & Park - Lower Parel"
  },
  {
    "id": "worli-sea-face-morning-yoga",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "st-regis-mumbai",
    "coordinates": [
      72.8240431,
      18.9941376
    ],
    "match": "The St. Regis Mumbai"
  },
  {
    "id": "itc-grand-central-parel",
    "coordinates": [
      72.8382792,
      18.9982254
    ],
    "match": "ITC Grand Central"
  },
  {
    "id": "worli-sea-face-premium-stays",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "lower-parel-mill-land-walk",
    "coordinates": [
      72.8302756,
      18.99568
    ],
    "match": "Lower Parel"
  },
  {
    "id": "lower-parel-business-park-green-loop",
    "coordinates": [
      72.8301949,
      19.0042547
    ],
    "match": "BMC Pay & Park - Lower Parel"
  },
  {
    "id": "lower-parel-barista-class",
    "coordinates": [
      72.8302756,
      18.99568
    ],
    "match": "Lower Parel"
  },
  {
    "id": "lower-parel-pottery-wheel-session",
    "coordinates": [
      72.8302756,
      18.99568
    ],
    "match": "Lower Parel"
  },
  {
    "id": "palladium-family-play-zone",
    "coordinates": [
      72.8236906,
      18.9953247
    ],
    "match": "Palladium West Zone"
  },
  {
    "id": "lower-parel-family-garden-evening",
    "coordinates": [
      72.8302756,
      18.99568
    ],
    "match": "Lower Parel"
  },
  {
    "id": "lower-parel-family-bowling-slot",
    "coordinates": [
      72.8302756,
      18.99568
    ],
    "match": "Lower Parel"
  },
  {
    "id": "lower-parel-family-dessert-walk",
    "coordinates": [
      72.8302756,
      18.99568
    ],
    "match": "Lower Parel"
  },
  {
    "id": "seawoods-grand-central-food-court",
    "coordinates": [
      73.0187243,
      19.0209279
    ],
    "match": "Seawoods Grand Central Tower 2"
  },
  {
    "id": "wonders-park-snack-carts",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "seawoods-grand-central-late-food-court",
    "coordinates": [
      73.0187243,
      19.0209279
    ],
    "match": "Seawoods Grand Central Tower 2"
  },
  {
    "id": "nerul-night-food-lanes",
    "coordinates": [
      73.0141116,
      19.0347072
    ],
    "match": "Nerul Village"
  },
  {
    "id": "wonders-park-evening-lights-walk",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "nerul-market-lanes",
    "coordinates": [
      73.0141116,
      19.0347072
    ],
    "match": "Nerul Village"
  },
  {
    "id": "seawoods-grand-central-retail",
    "coordinates": [
      73.0187243,
      19.0209279
    ],
    "match": "Seawoods Grand Central Tower 2"
  },
  {
    "id": "nerul-station-shopping-street",
    "coordinates": [
      73.0196832,
      19.0341403
    ],
    "match": "Nerul Railway Station"
  },
  {
    "id": "wonders-park-vendor-carts",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "wonders-park-climbing-wall",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "wonders-park-family-outing",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "nerul-lake-gardens",
    "coordinates": [
      73.020075,
      19.0302075
    ],
    "match": "Rock Garden, Nerul"
  },
  {
    "id": "nerul-waking-point-gardens",
    "coordinates": [
      73.020075,
      19.0302075
    ],
    "match": "Rock Garden, Nerul"
  },
  {
    "id": "seawoods-grand-central-area-hotels",
    "coordinates": [
      73.0187243,
      19.0209279
    ],
    "match": "Seawoods Grand Central Tower 2"
  },
  {
    "id": "seawoods-serviced-apartments",
    "coordinates": [
      73.0121104,
      19.0103007
    ],
    "match": "Seawoods Service Road"
  },
  {
    "id": "nerul-balaji-temple-visit",
    "coordinates": [
      73.0151541,
      19.0322371
    ],
    "match": "Mata Amritanandamayi Baug, opposite to Balaji Temple, nerul"
  },
  {
    "id": "wonders-park-green-lawns-walk",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "seawoods-grand-central-mangrove-edge",
    "coordinates": [
      73.0187243,
      19.0209279
    ],
    "match": "Seawoods Grand Central Tower 2"
  },
  {
    "id": "wonders-park-nerul-family-evening",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "wonders-park-mini-train-ride",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "nerul-gardens-picnic-evening",
    "coordinates": [
      73.020075,
      19.0302075
    ],
    "match": "Rock Garden, Nerul"
  },
  {
    "id": "old-panvel-wada-lane-eateries",
    "coordinates": [
      73.1112773,
      18.9875359
    ],
    "match": "Old Panvel Bhaji Market"
  },
  {
    "id": "panvel-station-khau-galli",
    "coordinates": [
      73.1232176,
      18.9907401
    ],
    "match": "Panvel Railway Station Bus Stop"
  },
  {
    "id": "old-panvel-misal-homes",
    "coordinates": [
      73.1112773,
      18.9875359
    ],
    "match": "Old Panvel Bhaji Market"
  },
  {
    "id": "old-panvel-night-market-lanes",
    "coordinates": [
      73.1112773,
      18.9875359
    ],
    "match": "Old Panvel Bhaji Market"
  },
  {
    "id": "panvel-old-market",
    "coordinates": [
      73.1112773,
      18.9875359
    ],
    "match": "Old Panvel Bhaji Market"
  },
  {
    "id": "panvel-station-market-street",
    "coordinates": [
      73.1232176,
      18.9907401
    ],
    "match": "Panvel Railway Station Bus Stop"
  },
  {
    "id": "malabar-hill-perimeter-walk",
    "coordinates": [
      72.8044801,
      18.9554402
    ],
    "match": "Malabar Hill Post Office"
  },
  {
    "id": "kamala-nehru-park-fitness-loop",
    "coordinates": [
      72.8046207,
      18.955096
    ],
    "match": "Kamala Nehru Park"
  },
  {
    "id": "kamala-nehru-park-morning-walk",
    "coordinates": [
      72.8046207,
      18.955096
    ],
    "match": "Kamala Nehru Park"
  },
  {
    "id": "hanging-gardens-terrace-loop",
    "coordinates": [
      72.8048197,
      18.9566065
    ],
    "match": "Pherozeshah Mehta Gardens (Hanging Gardens)"
  },
  {
    "id": "malabar-hill-viewpoint-garden",
    "coordinates": [
      72.8044801,
      18.9554402
    ],
    "match": "Malabar Hill Post Office"
  },
  {
    "id": "malabar-hill-boutique-stays",
    "coordinates": [
      72.8044801,
      18.9554402
    ],
    "match": "Malabar Hill Post Office"
  },
  {
    "id": "babulnath-temple-extension-visit",
    "coordinates": [
      72.8085682,
      18.958748
    ],
    "match": "Babunath Temple"
  },
  {
    "id": "hanging-gardens-canopy-walk",
    "coordinates": [
      72.8048197,
      18.9566065
    ],
    "match": "Pherozeshah Mehta Gardens (Hanging Gardens)"
  },
  {
    "id": "kamala-nehru-park-hedge-loops",
    "coordinates": [
      72.8046207,
      18.955096
    ],
    "match": "Kamala Nehru Park"
  },
  {
    "id": "malabar-hill-ridge-green-walk",
    "coordinates": [
      72.8044801,
      18.9554402
    ],
    "match": "Malabar Hill Post Office"
  },
  {
    "id": "hanging-gardens-sunset-viewpoint-lawn",
    "coordinates": [
      72.8048197,
      18.9566065
    ],
    "match": "Pherozeshah Mehta Gardens (Hanging Gardens)"
  },
  {
    "id": "kamala-nehru-park-family-playground",
    "coordinates": [
      72.8046207,
      18.955096
    ],
    "match": "Kamala Nehru Park"
  },
  {
    "id": "hanging-gardens-family-picnic",
    "coordinates": [
      72.8048197,
      18.9566065
    ],
    "match": "Pherozeshah Mehta Gardens (Hanging Gardens)"
  },
  {
    "id": "malabar-hill-family-sunset-slot",
    "coordinates": [
      72.8044801,
      18.9554402
    ],
    "match": "Malabar Hill Post Office"
  },
  {
    "id": "sewri-market-morning",
    "coordinates": [
      72.8542575,
      19.001418
    ],
    "match": "Sewri"
  },
  {
    "id": "vinay-health-home",
    "coordinates": [
      72.8128391,
      18.9747946
    ],
    "match": "Shetty Nursing Home (Shetty Health Services Pvt. Ltd.)"
  },
  {
    "id": "girgaon-chowpatty-night-bhel-stalls",
    "coordinates": [
      72.8219144,
      18.9523652
    ],
    "match": "Girgaon Chowpatty;Kranti Nagar"
  },
  {
    "id": "girgaon-market-lanes",
    "coordinates": [
      72.8179082,
      18.9543165
    ],
    "match": "Girgaon"
  },
  {
    "id": "thakurdwar-shopping-street",
    "coordinates": [
      72.8236381,
      18.9500139
    ],
    "match": "Thakurdwar"
  },
  {
    "id": "girgaon-chowpatty-kayaking-session",
    "coordinates": [
      72.8219144,
      18.9523652
    ],
    "match": "Girgaon Chowpatty;Kranti Nagar"
  },
  {
    "id": "girgaon-chowpatty-banana-ride-slot",
    "coordinates": [
      72.8219144,
      18.9523652
    ],
    "match": "Girgaon Chowpatty;Kranti Nagar"
  },
  {
    "id": "girgaon-chowpatty-evening-lounging",
    "coordinates": [
      72.8219144,
      18.9523652
    ],
    "match": "Girgaon Chowpatty;Kranti Nagar"
  },
  {
    "id": "babulnath-temple-courtyard-rest",
    "coordinates": [
      72.8085682,
      18.958748
    ],
    "match": "Babunath Temple"
  },
  {
    "id": "girgaon-wadi-gardens",
    "coordinates": [
      72.819606,
      18.9561838
    ],
    "match": "Girgaon wadi well (Khotachiwadi)"
  },
  {
    "id": "girgaon-chowpatty-seafront-lodges",
    "coordinates": [
      72.8219144,
      18.9523652
    ],
    "match": "Girgaon Chowpatty;Kranti Nagar"
  },
  {
    "id": "mumba-devi-temple-visit",
    "coordinates": [
      72.8307259,
      18.9519817
    ],
    "match": "Shree Mumbadevi Temple"
  },
  {
    "id": "babulnath-temple-quiet-hour",
    "coordinates": [
      72.8085682,
      18.958748
    ],
    "match": "Babunath Temple"
  },
  {
    "id": "walkeshwar-temple-lane-walk",
    "coordinates": [
      72.7932007,
      18.9456145
    ],
    "match": "Walkeshwar Temple"
  },
  {
    "id": "girgaon-chowpatty-morning-shoreline",
    "coordinates": [
      72.8219144,
      18.9523652
    ],
    "match": "Girgaon Chowpatty;Kranti Nagar"
  },
  {
    "id": "babulnath-temple-green-approach",
    "coordinates": [
      72.8085682,
      18.958748
    ],
    "match": "Babunath Temple"
  },
  {
    "id": "girgaon-chowpatty-family-beach-slot",
    "coordinates": [
      72.8219144,
      18.9523652
    ],
    "match": "Girgaon Chowpatty;Kranti Nagar"
  },
  {
    "id": "hill-road-bakery-strip",
    "coordinates": [
      72.8241777,
      19.0526477
    ],
    "match": "Hill Road Garden"
  },
  {
    "id": "hill-road-shopping-strip",
    "coordinates": [
      72.8241777,
      19.0526477
    ],
    "match": "Hill Road Garden"
  },
  {
    "id": "bandra-reclamation-weekend-market",
    "coordinates": [
      72.8326014,
      19.0512275
    ],
    "match": "Bandra Reclamation"
  },
  {
    "id": "st-paul-road-shoe-lanes",
    "coordinates": [
      72.8252243,
      19.0571775
    ],
    "match": "St. Paul Road"
  },
  {
    "id": "bandra-fort-seaside-walk",
    "coordinates": [
      72.818608,
      19.0420614
    ],
    "match": "Bandra Fort"
  },
  {
    "id": "bandra-worli-sea-link-cycling-slot",
    "coordinates": [
      72.8355111,
      19.0502023
    ],
    "match": "Bandra Worli Sea Link Flyover"
  },
  {
    "id": "bandra-reclamation-run-loop",
    "coordinates": [
      72.8326014,
      19.0512275
    ],
    "match": "Bandra Reclamation"
  },
  {
    "id": "bandra-bandstand-promenade",
    "coordinates": [
      72.8213412,
      19.0503626
    ],
    "match": "Bandstand Promenade"
  },
  {
    "id": "carter-road-promenade",
    "coordinates": [
      72.822656,
      19.0705997
    ],
    "match": "Carter Road Social"
  },
  {
    "id": "mount-mary-steps-walk",
    "coordinates": [
      72.8250874,
      19.0481917
    ],
    "match": "Mount Mary Steps"
  },
  {
    "id": "bandra-fort-garden",
    "coordinates": [
      72.818608,
      19.0420614
    ],
    "match": "Bandra Fort"
  },
  {
    "id": "bandra-reclamation-evening-walk",
    "coordinates": [
      72.8326014,
      19.0512275
    ],
    "match": "Bandra Reclamation"
  },
  {
    "id": "bandra-joggers-park-loop",
    "coordinates": [
      72.8213636,
      19.0594624
    ],
    "match": "Joggers' Park"
  },
  {
    "id": "taj-lands-end",
    "coordinates": [
      72.8196888,
      19.0435761
    ],
    "match": "Taj Lands End"
  },
  {
    "id": "bandra-west-serviced-apartments",
    "coordinates": [
      72.8302669,
      19.0583358
    ],
    "match": "Bandra West"
  },
  {
    "id": "carter-road-guesthouses",
    "coordinates": [
      72.822656,
      19.0705997
    ],
    "match": "Carter Road Social"
  },
  {
    "id": "mount-mary-basilica-visit",
    "coordinates": [
      72.8250874,
      19.0481917
    ],
    "match": "Mount Mary Steps"
  },
  {
    "id": "bandra-fort-heritage-hour",
    "coordinates": [
      72.818608,
      19.0420614
    ],
    "match": "Bandra Fort"
  },
  {
    "id": "st-andrews-church-visit",
    "coordinates": [
      72.8258007,
      19.0547676
    ],
    "match": "St. Andrew's Church"
  },
  {
    "id": "castella-de-aguada-ruin-visit",
    "coordinates": [
      72.8184995,
      19.0419788
    ],
    "match": "Castella de Aguada"
  },
  {
    "id": "bandra-heritage-home-facades-walk",
    "coordinates": [
      72.8246194,
      19.053611
    ],
    "match": "Sushama Patkar Maternity ( and Surgical) Home - Bandra"
  },
  {
    "id": "bandra-reclamation-garden-walk",
    "coordinates": [
      72.8326014,
      19.0512275
    ],
    "match": "Bandra Reclamation"
  },
  {
    "id": "bandra-west-bandstand-palm-walk",
    "coordinates": [
      72.8302669,
      19.0583358
    ],
    "match": "Bandra West"
  },
  {
    "id": "bandra-bandstand-family-evening",
    "coordinates": [
      72.8273311,
      19.0551005
    ],
    "match": "Bandra Holy Family Hospital Society Blood Bank"
  },
  {
    "id": "bandra-fort-family-picnic",
    "coordinates": [
      72.818608,
      19.0420614
    ],
    "match": "Bandra Fort"
  },
  {
    "id": "bandra-family-cycling-slot",
    "coordinates": [
      72.8273311,
      19.0551005
    ],
    "match": "Bandra Holy Family Hospital Society Blood Bank"
  },
  {
    "id": "bandra-family-garden-play-slot",
    "coordinates": [
      72.8273311,
      19.0551005
    ],
    "match": "Bandra Holy Family Hospital Society Blood Bank"
  },
  {
    "id": "govindas-at-iskcon-juhu",
    "coordinates": [
      72.8268798,
      19.1130667
    ],
    "match": "ISKCON Juhu Temple"
  },
  {
    "id": "juhu-beach-bhutta-carts",
    "coordinates": [
      72.826858,
      19.0971196
    ],
    "match": "Juhu Beach"
  },
  {
    "id": "novotel-juhu-beachfront-grills",
    "coordinates": [
      72.826858,
      19.0971196
    ],
    "match": "Juhu Beach"
  },
  {
    "id": "juhu-beach-night-food-stalls",
    "coordinates": [
      72.826858,
      19.0971196
    ],
    "match": "Juhu Beach"
  },
  {
    "id": "novotel-juhu-night-bar",
    "coordinates": [
      72.8347073,
      19.1153408
    ],
    "match": "Bar Stock Exchange Juhu"
  },
  {
    "id": "sun-n-sand-juhu-bar",
    "coordinates": [
      72.8347073,
      19.1153408
    ],
    "match": "Bar Stock Exchange Juhu"
  },
  {
    "id": "ramada-juhu-beach-bar",
    "coordinates": [
      72.826858,
      19.0971196
    ],
    "match": "Juhu Beach"
  },
  {
    "id": "juhu-boutique-strip",
    "coordinates": [
      72.8274295,
      19.1011649
    ],
    "match": "Juhu Residency Boutique Hotel"
  },
  {
    "id": "juhu-tara-road-weekend-stalls",
    "coordinates": [
      72.827208,
      19.0870555
    ],
    "match": "Kotak Mahindra ATM Juhu Tara road"
  },
  {
    "id": "juhu-beach-vendor-carts",
    "coordinates": [
      72.826858,
      19.0971196
    ],
    "match": "Juhu Beach"
  },
  {
    "id": "juhu-beach-volleyball-pickup",
    "coordinates": [
      72.826858,
      19.0971196
    ],
    "match": "Juhu Beach"
  },
  {
    "id": "juhu-beach-morning-run-loop",
    "coordinates": [
      72.826858,
      19.0971196
    ],
    "match": "Juhu Beach"
  },
  {
    "id": "juhu-versova-shoreline-walk",
    "coordinates": [
      72.8257301,
      19.1219328
    ],
    "match": "Juhu Versova Link Road"
  },
  {
    "id": "juhu-beach-lounging-stretch",
    "coordinates": [
      72.826858,
      19.0971196
    ],
    "match": "Juhu Beach"
  },
  {
    "id": "juhu-garden-morning-loop",
    "coordinates": [
      72.8340111,
      19.0841005
    ],
    "match": "Lions Juhu Garden"
  },
  {
    "id": "novotel-mumbai-juhu-beach",
    "coordinates": [
      72.826858,
      19.0971196
    ],
    "match": "Juhu Beach"
  },
  {
    "id": "sun-n-sand-juhu",
    "coordinates": [
      72.8241002,
      19.109493
    ],
    "match": "Sun-n-Sand"
  },
  {
    "id": "hotel-sea-princess",
    "coordinates": [
      72.8278496,
      19.0931831
    ],
    "match": "Hotel Sea Princess"
  },
  {
    "id": "ramada-plaza-juhu",
    "coordinates": [
      72.8246562,
      19.1095129
    ],
    "match": "Hotel Juhu Plaza"
  },
  {
    "id": "estella-juhu-beachside-stay",
    "coordinates": [
      72.826858,
      19.0971196
    ],
    "match": "Juhu Beach"
  },
  {
    "id": "juhu-service-apartments-row",
    "coordinates": [
      72.8286869,
      19.0931749
    ],
    "match": "The Emerald Hotel And Serviced Apartments"
  },
  {
    "id": "juhu-guesthouses-near-beach",
    "coordinates": [
      72.826858,
      19.0971196
    ],
    "match": "Juhu Beach"
  },
  {
    "id": "iskcon-juhu-temple-morning",
    "coordinates": [
      72.8268798,
      19.1130667
    ],
    "match": "ISKCON Juhu Temple"
  },
  {
    "id": "prithvi-theatre-matinee-visit",
    "coordinates": [
      72.8256355,
      19.1061914
    ],
    "match": "Prithvi Theatre"
  },
  {
    "id": "juhu-beach-sunrise-shoreline",
    "coordinates": [
      72.826858,
      19.0971196
    ],
    "match": "Juhu Beach"
  },
  {
    "id": "juhu-beach-family-sandcastles-evening",
    "coordinates": [
      72.826858,
      19.0971196
    ],
    "match": "Juhu Beach"
  },
  {
    "id": "juhu-family-beach-games-slot",
    "coordinates": [
      72.826858,
      19.0971196
    ],
    "match": "Juhu Beach"
  },
  {
    "id": "nom-nom-andheri",
    "coordinates": [
      72.8223454,
      19.1252302
    ],
    "match": "Nom Nom"
  },
  {
    "id": "four-bungalows-chaat-lane",
    "coordinates": [
      72.8255543,
      19.1287942
    ],
    "match": "Four Bungalows"
  },
  {
    "id": "andheri-west-pub-street",
    "coordinates": [
      72.833968,
      19.1172495
    ],
    "match": "Andheri West"
  },
  {
    "id": "infiniti-andheri-night-strip",
    "coordinates": [
      72.8309462,
      19.1412831
    ],
    "match": "Infiniti Mall Andheri"
  },
  {
    "id": "andheri-east-microbrewery-strip",
    "coordinates": [
      72.854202,
      19.1158835
    ],
    "match": "Andheri East"
  },
  {
    "id": "yeda-republic-andheri",
    "coordinates": [
      72.8254856,
      19.1092999
    ],
    "match": "Yeda Republic"
  },
  {
    "id": "versova-beach-night-cafes",
    "coordinates": [
      72.8133084,
      19.1299793
    ],
    "match": "Versova Beach"
  },
  {
    "id": "the-little-door-andheri",
    "coordinates": [
      72.8333522,
      19.1393909
    ],
    "match": "The Little Door"
  },
  {
    "id": "lokhandwala-market",
    "coordinates": [
      72.8246055,
      19.1430985
    ],
    "match": "Lokhandwala Complex"
  },
  {
    "id": "andheri-west-street-shopping",
    "coordinates": [
      72.833968,
      19.1172495
    ],
    "match": "Andheri West"
  },
  {
    "id": "four-bungalows-market",
    "coordinates": [
      72.8255543,
      19.1287942
    ],
    "match": "Four Bungalows"
  },
  {
    "id": "andheri-east-wholesale-lanes",
    "coordinates": [
      72.854202,
      19.1158835
    ],
    "match": "Andheri East"
  },
  {
    "id": "versova-beach-horse-riding-slot",
    "coordinates": [
      72.8133084,
      19.1299793
    ],
    "match": "Versova Beach"
  },
  {
    "id": "versova-beach-evening-sit-outs",
    "coordinates": [
      72.8133084,
      19.1299793
    ],
    "match": "Versova Beach"
  },
  {
    "id": "andheri-sports-complex",
    "coordinates": [
      72.8373653,
      19.1274759
    ],
    "match": "Andheri Sports Complex"
  },
  {
    "id": "seven-bungalow-garden-walk",
    "coordinates": [
      72.8171122,
      19.1287083
    ],
    "match": "Seven Bungalows Garden"
  },
  {
    "id": "four-bungalow-park-loop",
    "coordinates": [
      72.8255543,
      19.1287942
    ],
    "match": "Four Bungalows"
  },
  {
    "id": "lemon-tree-andheri-west",
    "coordinates": [
      72.833968,
      19.1172495
    ],
    "match": "Andheri West"
  },
  {
    "id": "courtyard-by-marriott-andheri-east",
    "coordinates": [
      72.854202,
      19.1158835
    ],
    "match": "Andheri East"
  },
  {
    "id": "hyatt-regency-andheri-east",
    "coordinates": [
      72.854202,
      19.1158835
    ],
    "match": "Andheri East"
  },
  {
    "id": "holiday-inn-andheri-east",
    "coordinates": [
      72.854202,
      19.1158835
    ],
    "match": "Andheri East"
  },
  {
    "id": "radisson-mumbai-andheri-east",
    "coordinates": [
      72.854202,
      19.1158835
    ],
    "match": "Andheri East"
  },
  {
    "id": "andheri-west-boutique-hotels",
    "coordinates": [
      72.833968,
      19.1172495
    ],
    "match": "Andheri West"
  },
  {
    "id": "lokhandwala-serviced-apartments",
    "coordinates": [
      72.8286869,
      19.0931749
    ],
    "match": "The Emerald Hotel And Serviced Apartments"
  },
  {
    "id": "versova-beach-homestays",
    "coordinates": [
      72.8133084,
      19.1299793
    ],
    "match": "Versova Beach"
  },
  {
    "id": "andheri-east-village-church-visit",
    "coordinates": [
      72.854202,
      19.1158835
    ],
    "match": "Andheri East"
  },
  {
    "id": "versova-beach-shoreline-walk",
    "coordinates": [
      72.8133084,
      19.1299793
    ],
    "match": "Versova Beach"
  },
  {
    "id": "four-bungalows-seaside-garden",
    "coordinates": [
      72.8255543,
      19.1287942
    ],
    "match": "Four Bungalows"
  },
  {
    "id": "versova-beach-family-evening",
    "coordinates": [
      72.8133084,
      19.1299793
    ],
    "match": "Versova Beach"
  },
  {
    "id": "lokhandwala-family-garden-slot",
    "coordinates": [
      72.8269168,
      19.145163
    ],
    "match": "Lokhandwala Garden"
  },
  {
    "id": "versova-family-fishing-village-walk",
    "coordinates": [
      72.8060957,
      19.1384723
    ],
    "match": "BMC Versova Village Sewage Water Pumping Station"
  },
  {
    "id": "aarey-dairy-canteen",
    "coordinates": [
      72.8781375,
      19.1548558
    ],
    "match": "Aarey Central Dairy"
  },
  {
    "id": "aarey-dairy-produce-stalls",
    "coordinates": [
      72.8781375,
      19.1548558
    ],
    "match": "Aarey Central Dairy"
  },
  {
    "id": "aarey-milk-colony-trail-network",
    "coordinates": [
      72.8707223,
      19.1561292
    ],
    "match": "Aarey Milk Colony"
  },
  {
    "id": "aarey-picnic-meadows",
    "coordinates": [
      72.8822677,
      19.1366368
    ],
    "match": "Aarey Picnic Spot"
  },
  {
    "id": "aarey-dairy-heritage-extension",
    "coordinates": [
      72.8781375,
      19.1548558
    ],
    "match": "Aarey Central Dairy"
  },
  {
    "id": "aarey-colony-green-trail",
    "coordinates": [
      72.8707223,
      19.1561292
    ],
    "match": "Aarey Milk Colony"
  },
  {
    "id": "aarey-unit-16-meadow-walk",
    "coordinates": [
      72.8786324,
      19.1306855
    ],
    "match": "Aarey Unit 19"
  },
  {
    "id": "aarey-milk-colony-shady-lanes",
    "coordinates": [
      72.8707223,
      19.1561292
    ],
    "match": "Aarey Milk Colony"
  },
  {
    "id": "aarey-family-picnic-meadow",
    "coordinates": [
      72.8822677,
      19.1366368
    ],
    "match": "Aarey Picnic Spot"
  },
  {
    "id": "aarey-family-dairy-visit",
    "coordinates": [
      72.8781375,
      19.1548558
    ],
    "match": "Aarey Central Dairy"
  },
  {
    "id": "kanheri-base-tea-stalls",
    "coordinates": [
      72.8612465,
      19.2018265
    ],
    "match": "Jai Mata Di Tea Stall"
  },
  {
    "id": "borivali-station-food-street",
    "coordinates": [
      72.8576719,
      19.2293737
    ],
    "match": "Borivali Station (East)"
  },
  {
    "id": "borivali-station-late-food-street",
    "coordinates": [
      72.8576719,
      19.2293737
    ],
    "match": "Borivali Station (East)"
  },
  {
    "id": "borivali-station-shopping-street",
    "coordinates": [
      72.8576719,
      19.2293737
    ],
    "match": "Borivali Station (East)"
  },
  {
    "id": "rivali-park-retail-strip",
    "coordinates": [
      72.8656993,
      19.2169357
    ],
    "match": "Rivali Park Road"
  },
  {
    "id": "kanheri-caves-trek-inside-sgnp",
    "coordinates": [
      72.8947398,
      19.2144265
    ],
    "match": "Kanheri Caves Road"
  },
  {
    "id": "borivali-national-park-cycling-loop",
    "coordinates": [
      72.8636162,
      19.2305823
    ],
    "match": "Borivali National Park"
  },
  {
    "id": "sgnp-lion-safari-viewing",
    "coordinates": [
      72.8884927,
      19.2418107
    ],
    "match": "Lion Safari Road"
  },
  {
    "id": "borivali-budget-hotel-row",
    "coordinates": [
      72.864763,
      19.244507
    ],
    "match": "Ganesh Nagar / Gokul Anand Hotel Borivali East"
  },
  {
    "id": "kanheri-caves-heritage-extension",
    "coordinates": [
      72.8947398,
      19.2144265
    ],
    "match": "Kanheri Caves Road"
  },
  {
    "id": "borivali-east-indian-community-lanes",
    "coordinates": [
      72.8576319,
      19.2299554
    ],
    "match": "Borivali  RS (East)"
  },
  {
    "id": "sgnp-lion-safari-family-slot",
    "coordinates": [
      72.8884927,
      19.2418107
    ],
    "match": "Lion Safari Road"
  },
  {
    "id": "inorbit-vashi-food-court",
    "coordinates": [
      73.0012609,
      19.0660377
    ],
    "match": "Inorbit Mall Vashi"
  },
  {
    "id": "palm-beach-road-cafes",
    "coordinates": [
      73.0050477,
      19.0551885
    ],
    "match": "Palm Beach Service Road"
  },
  {
    "id": "vashi-station-dosa-counters",
    "coordinates": [
      72.9984708,
      19.0764046
    ],
    "match": "Vashi Fire Station"
  },
  {
    "id": "inorbit-vashi-late-food-court",
    "coordinates": [
      73.0012609,
      19.0660377
    ],
    "match": "Inorbit Mall Vashi"
  },
  {
    "id": "palm-beach-galleria-evening-strip",
    "coordinates": [
      73.0077005,
      19.0850238
    ],
    "match": "Palm Beach Galleria Mall"
  },
  {
    "id": "vashi-station-night-food-lanes",
    "coordinates": [
      72.9984708,
      19.0764046
    ],
    "match": "Vashi Fire Station"
  },
  {
    "id": "vashi-market",
    "coordinates": [
      72.9804748,
      19.0641486
    ],
    "match": "Vashi Toll Plaza"
  },
  {
    "id": "inorbit-mall-vashi",
    "coordinates": [
      73.0012609,
      19.0660377
    ],
    "match": "Inorbit Mall Vashi"
  },
  {
    "id": "vashi-station-shopping-lanes",
    "coordinates": [
      72.9984708,
      19.0764046
    ],
    "match": "Vashi Fire Station"
  },
  {
    "id": "sector-17-market-vashi",
    "coordinates": [
      73.0073637,
      19.0893575
    ],
    "match": "Sector 29 Vashi Road"
  },
  {
    "id": "palm-beach-galleria",
    "coordinates": [
      73.0077005,
      19.0850238
    ],
    "match": "Palm Beach Galleria Mall"
  },
  {
    "id": "vashi-mini-seashore-paddle-session",
    "coordinates": [
      72.9929328,
      19.0817346
    ],
    "match": "mini seashore"
  },
  {
    "id": "vashi-mini-seashore-park",
    "coordinates": [
      72.9929328,
      19.0817346
    ],
    "match": "mini seashore"
  },
  {
    "id": "inorbit-vashi-leisure-zone",
    "coordinates": [
      73.0012609,
      19.0660377
    ],
    "match": "Inorbit Mall Vashi"
  },
  {
    "id": "vashi-heritage-village-lanes",
    "coordinates": [
      72.9867412,
      19.0683314
    ],
    "match": "Vashi Village"
  },
  {
    "id": "st-marys-church-vashi-visit",
    "coordinates": [
      72.9953201,
      19.0820142
    ],
    "match": "St. Mary's Junior College"
  },
  {
    "id": "vashi-mini-seashore-walk-extension",
    "coordinates": [
      72.9929328,
      19.0817346
    ],
    "match": "mini seashore"
  },
  {
    "id": "vashi-mini-seashore-family-evening",
    "coordinates": [
      72.9929328,
      19.0817346
    ],
    "match": "mini seashore"
  },
  {
    "id": "cbd-belapur-eateries",
    "coordinates": [
      73.0408354,
      19.0232189
    ],
    "match": "CBD Belapur ST Bus Stop"
  },
  {
    "id": "belapur-station-lunch-lanes",
    "coordinates": [
      73.0398886,
      19.0209123
    ],
    "match": "C.B.D.Belapur Railway Station"
  },
  {
    "id": "cbd-belapur-evening-eateries",
    "coordinates": [
      73.0408354,
      19.0232189
    ],
    "match": "CBD Belapur ST Bus Stop"
  },
  {
    "id": "belapur-station-night-lanes",
    "coordinates": [
      73.0398886,
      19.0209123
    ],
    "match": "C.B.D.Belapur Railway Station"
  },
  {
    "id": "cbd-belapur-market",
    "coordinates": [
      73.0408354,
      19.0232189
    ],
    "match": "CBD Belapur ST Bus Stop"
  },
  {
    "id": "belapur-station-shopping-lanes",
    "coordinates": [
      73.0398886,
      19.0209123
    ],
    "match": "C.B.D.Belapur Railway Station"
  },
  {
    "id": "belapur-fort-hill-climb",
    "coordinates": [
      73.0287773,
      19.0088415
    ],
    "match": "Belapur Fort"
  },
  {
    "id": "belapur-parsik-hill-ridge-walk",
    "coordinates": [
      73.0291933,
      19.0225814
    ],
    "match": "Parsik Hill Viewpoint"
  },
  {
    "id": "belapur-fort-garden-walk",
    "coordinates": [
      73.0287773,
      19.0088415
    ],
    "match": "Belapur Fort"
  },
  {
    "id": "cbd-belapur-central-gardens",
    "coordinates": [
      73.0391304,
      19.0190075
    ],
    "match": "CBD Belapur"
  },
  {
    "id": "cbd-belapur-business-hotels",
    "coordinates": [
      73.0408354,
      19.0232189
    ],
    "match": "CBD Belapur ST Bus Stop"
  },
  {
    "id": "belapur-fort-heritage-extension",
    "coordinates": [
      73.0287773,
      19.0088415
    ],
    "match": "Belapur Fort"
  },
  {
    "id": "belapur-village-temple-visit",
    "coordinates": [
      73.0303857,
      19.013418
    ],
    "match": "Belapur Village"
  },
  {
    "id": "belapur-fort-green-trail",
    "coordinates": [
      73.0287773,
      19.0088415
    ],
    "match": "Belapur Fort"
  },
  {
    "id": "belapur-cbd-mangrove-belt",
    "coordinates": [
      73.0408354,
      19.0232189
    ],
    "match": "CBD Belapur ST Bus Stop"
  },
  {
    "id": "belapur-fort-family-picnic",
    "coordinates": [
      73.0287773,
      19.0088415
    ],
    "match": "Belapur Fort"
  },
  {
    "id": "cbd-belapur-gardens-family-outing",
    "coordinates": [
      73.0408354,
      19.0232189
    ],
    "match": "CBD Belapur ST Bus Stop"
  },
  {
    "id": "utsav-chowk-snack-counters",
    "coordinates": [
      73.0589404,
      19.0326108
    ],
    "match": "Utsav Chowk"
  },
  {
    "id": "little-world-food-court",
    "coordinates": [
      73.0664402,
      19.0306929
    ],
    "match": "Little World Mall"
  },
  {
    "id": "kharghar-station-food-street",
    "coordinates": [
      73.058951,
      19.0264976
    ],
    "match": "Kharghar Railway Station"
  },
  {
    "id": "central-park-evening-food-carts",
    "coordinates": [
      73.0759837,
      19.0536797
    ],
    "match": "Central Park"
  },
  {
    "id": "utsav-chowk-night-promenade",
    "coordinates": [
      73.0589404,
      19.0326108
    ],
    "match": "Utsav Chowk"
  },
  {
    "id": "central-park-kharghar-evening-lights",
    "coordinates": [
      73.0759837,
      19.0536797
    ],
    "match": "Central Park"
  },
  {
    "id": "kharghar-station-night-food-street",
    "coordinates": [
      73.058951,
      19.0264976
    ],
    "match": "Kharghar Railway Station"
  },
  {
    "id": "little-world-late-food-court",
    "coordinates": [
      73.0664402,
      19.0306929
    ],
    "match": "Little World Mall"
  },
  {
    "id": "utsav-chowk-night-chai-stalls",
    "coordinates": [
      73.0589404,
      19.0326108
    ],
    "match": "Utsav Chowk"
  },
  {
    "id": "kharghar-station-market",
    "coordinates": [
      73.058951,
      19.0264976
    ],
    "match": "Kharghar Railway Station"
  },
  {
    "id": "utsav-chowk-bazaar-stalls",
    "coordinates": [
      73.0589404,
      19.0326108
    ],
    "match": "Utsav Chowk"
  },
  {
    "id": "central-park-vendor-rows",
    "coordinates": [
      73.0759837,
      19.0536797
    ],
    "match": "Central Park"
  },
  {
    "id": "kharghar-valley-trail-run",
    "coordinates": [
      73.0605763,
      19.0546192
    ],
    "match": "Kharghar Valley Golf Course"
  },
  {
    "id": "central-park-cycling-loop",
    "coordinates": [
      73.0759837,
      19.0536797
    ],
    "match": "Central Park"
  },
  {
    "id": "utsav-chowk-evening-promenade",
    "coordinates": [
      73.0589404,
      19.0326108
    ],
    "match": "Utsav Chowk"
  },
  {
    "id": "kharghar-valley-view-garden",
    "coordinates": [
      73.0605763,
      19.0546192
    ],
    "match": "Kharghar Valley Golf Course"
  },
  {
    "id": "central-park-adjacent-stays",
    "coordinates": [
      73.0759837,
      19.0536797
    ],
    "match": "Central Park"
  },
  {
    "id": "kharghar-village-heritage-walk",
    "coordinates": [
      73.0712178,
      19.0452594
    ],
    "match": "Kharghar Village"
  },
  {
    "id": "kharghar-valley-green-belt",
    "coordinates": [
      73.0605763,
      19.0546192
    ],
    "match": "Kharghar Valley Golf Course"
  },
  {
    "id": "kharghar-watercolour-class",
    "coordinates": [
      73.0702648,
      19.0365104
    ],
    "match": "Kharghar Water Station"
  },
  {
    "id": "central-park-toy-train-ride",
    "coordinates": [
      73.0759837,
      19.0536797
    ],
    "match": "Central Park"
  },
  {
    "id": "little-world-mall-family-zone",
    "coordinates": [
      73.0664402,
      19.0306929
    ],
    "match": "Little World Mall"
  },
  {
    "id": "kharghar-valley-boating-slot",
    "coordinates": [
      73.0605763,
      19.0546192
    ],
    "match": "Kharghar Valley Golf Course"
  },
  {
    "id": "airoli-food-street",
    "coordinates": [
      72.9928877,
      19.1633186
    ],
    "match": "Airoli Gaon"
  },
  {
    "id": "airoli-night-food-street",
    "coordinates": [
      72.9928877,
      19.1633186
    ],
    "match": "Airoli Gaon"
  },
  {
    "id": "airoli-market",
    "coordinates": [
      72.9928877,
      19.1633186
    ],
    "match": "Airoli Gaon"
  },
  {
    "id": "airoli-station-shopping-street",
    "coordinates": [
      73.0001254,
      19.1598907
    ],
    "match": "Airoli Railway Station"
  },
  {
    "id": "airoli-weekend-bazaar",
    "coordinates": [
      72.9995919,
      19.1502418
    ],
    "match": "Sahakar Bazaar-Airoli"
  },
  {
    "id": "airoli-knowledge-park-garden",
    "coordinates": [
      72.9903341,
      19.1787757
    ],
    "match": "Capgemini Knowledge Park"
  },
  {
    "id": "airoli-sector-30-gardens",
    "coordinates": [
      72.9992452,
      19.1481221
    ],
    "match": "Sector 5-Airoli"
  },
  {
    "id": "airoli-business-hotels",
    "coordinates": [
      73.002037,
      19.1690599
    ],
    "match": "होटल मुंबई हाउस ऐरोली, नवी मुम्बई"
  },
  {
    "id": "airoli-village-temple-visit",
    "coordinates": [
      72.9928877,
      19.1633186
    ],
    "match": "Airoli Gaon"
  },
  {
    "id": "airoli-mangrove-park-nature-trail",
    "coordinates": [
      72.9902248,
      19.1622469
    ],
    "match": "नवी मुंबई महानगरपालिका अधिकृत पार्क, ऐरोली सेक्टर २०"
  },
  {
    "id": "airoli-knowledge-park-family-walk",
    "coordinates": [
      72.9903341,
      19.1787757
    ],
    "match": "Capgemini Knowledge Park"
  },
  {
    "id": "airoli-family-garden-picnic",
    "coordinates": [
      72.9978122,
      19.1449005
    ],
    "match": "Airoli Sec 6 Garden"
  },
  {
    "id": "worli-sea-face-evening-food-carts",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "worli-koliwada-craft-carts",
    "coordinates": [
      72.8173559,
      19.0215609
    ],
    "match": "Worli Koliwada"
  },
  {
    "id": "worli-sea-face-cycling-loop",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "worli-fort-edge-walk",
    "coordinates": [
      72.8168396,
      19.0237565
    ],
    "match": "Worli Fort"
  },
  {
    "id": "worli-sea-face-promenade",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "worli-fort-courtyard",
    "coordinates": [
      72.8168396,
      19.0237565
    ],
    "match": "Worli Fort"
  },
  {
    "id": "worli-koliwada-jetty-walk",
    "coordinates": [
      72.8173559,
      19.0215609
    ],
    "match": "Worli Koliwada"
  },
  {
    "id": "worli-koliwada-homestays-edge",
    "coordinates": [
      72.8173559,
      19.0215609
    ],
    "match": "Worli Koliwada"
  },
  {
    "id": "worli-fort-heritage-visit",
    "coordinates": [
      72.8168396,
      19.0237565
    ],
    "match": "Worli Fort"
  },
  {
    "id": "worli-koliwada-heritage-walk",
    "coordinates": [
      72.8173559,
      19.0215609
    ],
    "match": "Worli Koliwada"
  },
  {
    "id": "haji-ali-causeway-walk",
    "coordinates": [
      72.8093021,
      18.981245
    ],
    "match": "Haji Ali Causeway"
  },
  {
    "id": "worli-sea-face-breeze-walk",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "worli-fort-coastal-edge",
    "coordinates": [
      72.8168396,
      19.0237565
    ],
    "match": "Worli Fort"
  },
  {
    "id": "worli-sea-face-banyan-corner",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "worli-sea-face-family-evening-walk",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "worli-fort-family-picnic",
    "coordinates": [
      72.8168396,
      19.0237565
    ],
    "match": "Worli Fort"
  },
  {
    "id": "worli-family-garden-play-slot",
    "coordinates": [
      72.8166244,
      19.0145962
    ],
    "match": "Worli Sea Face Garden"
  },
  {
    "id": "waterfield-road-boutiques",
    "coordinates": [
      72.8346902,
      19.0640656
    ],
    "match": "RK Patkar Marg (Waterfield Road)"
  },
  {
    "id": "hotel-bandra-residency",
    "coordinates": [
      72.8325298,
      19.0617235
    ],
    "match": "Grand Residency Hotel"
  },
  {
    "id": "waterfield-road-design-hostels",
    "coordinates": [
      72.8346902,
      19.0640656
    ],
    "match": "RK Patkar Marg (Waterfield Road)"
  },
  {
    "id": "bandra-east-indian-village-lanes",
    "coordinates": [
      72.8498111,
      19.0616565
    ],
    "match": "Bandra East"
  },
  {
    "id": "shiv-sagar-veg",
    "coordinates": [
      72.8461004,
      19.0981963
    ],
    "match": "Shiv Sagar Hotel"
  },
  {
    "id": "versova-beach-lounging",
    "coordinates": [
      72.8235734,
      19.1009687
    ],
    "match": "Danda-Juhu-Versova beach walk"
  },
  {
    "id": "chhota-kashmir-tea-stalls",
    "coordinates": [
      72.8696437,
      19.1294255
    ],
    "match": "Tea Stall"
  },
  {
    "id": "worli-bandra-sea-link-run-slot",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "borivali-west-business-hotels",
    "coordinates": [
      72.864763,
      19.244507
    ],
    "match": "Ganesh Nagar / Gokul Anand Hotel Borivali East"
  },
  {
    "id": "palm-beach-evening-benches",
    "coordinates": [
      73.0016203,
      19.0640394
    ],
    "match": "Palm Beach Marg"
  },
  {
    "id": "palm-beach-shoreline-walk",
    "coordinates": [
      73.0016203,
      19.0640394
    ],
    "match": "Palm Beach Marg"
  },
  {
    "id": "seawoods-creek-side-park",
    "coordinates": [
      73.0162916,
      19.0132303
    ],
    "match": "Seawoods Theme Park"
  },
  {
    "id": "seawoods-utsav-estate-gardens",
    "coordinates": [
      73.0160048,
      19.0068821
    ],
    "match": "Seawoods Estates Road"
  },
  {
    "id": "kharghar-taloja-hills-traverse",
    "coordinates": [
      73.0446834,
      19.0512484
    ],
    "match": "Kharghar Hills Viewing Platform"
  },
  {
    "id": "kharghar-hills-base-garden",
    "coordinates": [
      73.0446834,
      19.0512484
    ],
    "match": "Kharghar Hills Viewing Platform"
  },
  {
    "id": "kharghar-hills-base-nature-trail",
    "coordinates": [
      73.0446834,
      19.0512484
    ],
    "match": "Kharghar Hills Viewing Platform"
  },
  {
    "id": "airoli-creek-side-guesthouses",
    "coordinates": [
      72.9902398,
      19.1739259
    ],
    "match": "Capgemini Airoli ERC Guest House"
  },
  {
    "id": "worli-sea-link-view-hotels",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  }
];
