// Generated by scripts/geocode-places.ts - do not edit by hand.
// Every coordinate was matched against OpenStreetMap via Nominatim and
// validated against its area anchor. Missing ids fall back to the
// area-anchor pin with an honest demo-estimate confidence label.
export type GeocodedPlace = { id: string; coordinates: [number, number]; match: string };

export const geocodedPlaces: GeocodedPlace[] = [
  {
    "id": "kyani-co",
    "coordinates": [
      72.8287886,
      18.9441069
    ],
    "match": "Kyani & Co."
  },
  {
    "id": "britannia-co",
    "coordinates": [
      72.8398242,
      18.9323318
    ],
    "match": "Britannia Cafe"
  },
  {
    "id": "yazdani-bakery",
    "coordinates": [
      72.8336019,
      18.9331806
    ],
    "match": "Yazdani Bakery"
  },
  {
    "id": "cafe-military",
    "coordinates": [
      72.8320601,
      18.9307521
    ],
    "match": "Cafe Military"
  },
  {
    "id": "ideal-corner",
    "coordinates": [
      72.8342167,
      18.9349624
    ],
    "match": "Ideal Corner"
  },
  {
    "id": "khyber",
    "coordinates": [
      72.8316572,
      18.9283232
    ],
    "match": "Khyber"
  },
  {
    "id": "trishna",
    "coordinates": [
      72.8323932,
      18.9286576
    ],
    "match": "Trishna"
  },
  {
    "id": "gokul",
    "coordinates": [
      72.8317135,
      18.9447424
    ],
    "match": "गोकुळदास तेजपाल रुग्णालय"
  },
  {
    "id": "kala-ghoda-gallery-night-walks",
    "coordinates": [
      72.8325994,
      18.9284581
    ],
    "match": "Kala Ghoda"
  },
  {
    "id": "ballard-estate-evening-strip",
    "coordinates": [
      72.8391325,
      18.9366512
    ],
    "match": "Ballard Estate"
  },
  {
    "id": "crawford-market",
    "coordinates": [
      72.8351907,
      18.9485665
    ],
    "match": "Crawford Market"
  },
  {
    "id": "mangaldas-market",
    "coordinates": [
      72.8324053,
      18.9482039
    ],
    "match": "Mangaldas Market"
  },
  {
    "id": "zaveri-bazaar",
    "coordinates": [
      72.8245855,
      18.9383478
    ],
    "match": "Zaver Mahal"
  },
  {
    "id": "abdul-rehman-street",
    "coordinates": [
      72.8319585,
      18.9532135
    ],
    "match": "Abdul Rehman Street"
  },
  {
    "id": "cn-naik-market",
    "coordinates": [
      72.8295989,
      18.9411989
    ],
    "match": "Naik Bus Stop"
  },
  {
    "id": "azad-maidan-fitness-track",
    "coordinates": [
      72.832942,
      18.9415557
    ],
    "match": "Azad Maidan Police Station"
  },
  {
    "id": "horniman-circle-garden",
    "coordinates": [
      72.8350219,
      18.9319765
    ],
    "match": "Horniman Circle Garden"
  },
  {
    "id": "azad-maidan-lounging",
    "coordinates": [
      72.832942,
      18.9415557
    ],
    "match": "Azad Maidan Police Station"
  },
  {
    "id": "cross-maidan-evening-walk",
    "coordinates": [
      72.8296103,
      18.937434
    ],
    "match": "Cross Maidan"
  },
  {
    "id": "grand-hotel-fort",
    "coordinates": [
      72.8408238,
      18.9361901
    ],
    "match": "Grand Hotel"
  },
  {
    "id": "hotel-marine-plaza",
    "coordinates": [
      72.8340885,
      18.9356647
    ],
    "match": "Hotel Fountain Plaza"
  },
  {
    "id": "hotel-harbour-view-fort",
    "coordinates": [
      72.8318466,
      18.9187992
    ],
    "match": "Hotel Harbour View"
  },
  {
    "id": "hotel-godwin-colaba-fort-edge",
    "coordinates": [
      72.8305236,
      18.9189927
    ],
    "match": "Hotel Godwin"
  },
  {
    "id": "chhatrapati-shivaji-maharaj-terminus-heritage-walk",
    "coordinates": [
      72.8318464,
      18.9407842
    ],
    "match": "Chhatrapati Shivaji Maharaj Terminus"
  },
  {
    "id": "asiatic-society-steps",
    "coordinates": [
      72.8361416,
      18.9318316
    ],
    "match": "Asiatic Society Town Hall;Asiatic Society Municipal Library"
  },
  {
    "id": "rbi-monetary-museum",
    "coordinates": [
      72.8361829,
      18.934005
    ],
    "match": "RBI Monetary Museum"
  },
  {
    "id": "st-thomas-cathedral",
    "coordinates": [
      72.8336828,
      18.9318595
    ],
    "match": "St Thomas Cathedral"
  },
  {
    "id": "elphinstone-college-facade-walk",
    "coordinates": [
      72.8302832,
      18.9434192
    ],
    "match": "Elphinstone Technical High School and Junior College Mumbai"
  },
  {
    "id": "david-sassoon-library-extension-visit",
    "coordinates": [
      72.8311551,
      18.9276912
    ],
    "match": "Sir David Sassoon Library"
  },
  {
    "id": "horniman-circle-heritage-loop",
    "coordinates": [
      72.8342863,
      18.9321217
    ],
    "match": "Horniman Circle"
  },
  {
    "id": "bombay-samachar-building-walk",
    "coordinates": [
      72.8339592,
      18.9298205
    ],
    "match": "Bombay Samachar Marg"
  },
  {
    "id": "gateway-of-india-heritage-hour",
    "coordinates": [
      72.8345228,
      18.9229191
    ],
    "match": "Gateway of India - Mandwa Rewas Ferry Terminal"
  },
  {
    "id": "regal-cinema-art-deco-visit",
    "coordinates": [
      72.8325192,
      18.9245934
    ],
    "match": "Regal Cinema"
  },
  {
    "id": "fort-art-deco-trail",
    "coordinates": [
      72.8306139,
      18.9293596
    ],
    "match": "विक्टोरिया गोथिक और आर्ट डेका इन्सेंबल्स ऑफ़ मुंबई"
  },
  {
    "id": "municipal-corporation-building-view-stop",
    "coordinates": [
      72.8342181,
      18.940677
    ],
    "match": "Municipal Corporation of Greater Mumbai"
  },
  {
    "id": "kala-ghoda-gallery-evening",
    "coordinates": [
      72.8325994,
      18.9284581
    ],
    "match": "Kala Ghoda"
  },
  {
    "id": "jehangir-art-gallery-visit",
    "coordinates": [
      72.8317177,
      18.9272846
    ],
    "match": "Jehangir Art Gallery"
  },
  {
    "id": "flora-fountain-art-deco-stop",
    "coordinates": [
      72.8306139,
      18.9293596
    ],
    "match": "विक्टोरिया गोथिक और आर्ट डेका इन्सेंबल्स ऑफ़ मुंबई"
  },
  {
    "id": "horniman-circle-canopy-hour",
    "coordinates": [
      72.8342863,
      18.9321217
    ],
    "match": "Horniman Circle"
  },
  {
    "id": "cross-maidan-green-hour",
    "coordinates": [
      72.8296103,
      18.937434
    ],
    "match": "Cross Maidan"
  },
  {
    "id": "azad-maidan-morning-green-loop",
    "coordinates": [
      72.832942,
      18.9415557
    ],
    "match": "Azad Maidan Police Station"
  },
  {
    "id": "cooperage-garden-shade-walk",
    "coordinates": [
      72.8288833,
      18.9257208
    ],
    "match": "Cooperage Garden"
  },
  {
    "id": "kala-ghoda-sketch-walk-workshop",
    "coordinates": [
      72.8325994,
      18.9284581
    ],
    "match": "Kala Ghoda"
  },
  {
    "id": "kala-ghoda-photography-walk-class",
    "coordinates": [
      72.8325994,
      18.9284581
    ],
    "match": "Kala Ghoda"
  },
  {
    "id": "horniman-circle-family-picnic",
    "coordinates": [
      72.8342863,
      18.9321217
    ],
    "match": "Horniman Circle"
  },
  {
    "id": "horniman-circle-family-play-slot",
    "coordinates": [
      72.8342863,
      18.9321217
    ],
    "match": "Horniman Circle"
  },
  {
    "id": "leopold-cafe",
    "coordinates": [
      72.8317641,
      18.9227133
    ],
    "match": "Cafe Leopold"
  },
  {
    "id": "cafe-mondegar",
    "coordinates": [
      72.8321786,
      18.9240421
    ],
    "match": "Cafe Mondegar"
  },
  {
    "id": "baghdadi",
    "coordinates": [
      72.8324423,
      18.9229102
    ],
    "match": "बगदादी रेस्टोरेंट"
  },
  {
    "id": "bademiya-kebab-stall",
    "coordinates": [
      72.8325111,
      18.9231497
    ],
    "match": "Bademiya Seekh Kebab Stall"
  },
  {
    "id": "theobroma-colaba",
    "coordinates": [
      72.8292274,
      18.9192171
    ],
    "match": "Theobroma"
  },
  {
    "id": "cafe-churchill",
    "coordinates": [
      72.8302321,
      18.919922
    ],
    "match": "Cafe Churchill"
  },
  {
    "id": "woodside-inn",
    "coordinates": [
      72.8318781,
      18.9249021
    ],
    "match": "Woodside Inn"
  },
  {
    "id": "harbour-view-bar-colaba",
    "coordinates": [
      72.8318466,
      18.9187992
    ],
    "match": "Hotel Harbour View"
  },
  {
    "id": "indigo-colaba",
    "coordinates": [
      72.8320651,
      18.9222725
    ],
    "match": "Indigo"
  },
  {
    "id": "cafe-mondegar-night-jukebox",
    "coordinates": [
      72.8321786,
      18.9240421
    ],
    "match": "Cafe Mondegar"
  },
  {
    "id": "woodside-inn-night-strip",
    "coordinates": [
      72.8318781,
      18.9249021
    ],
    "match": "Woodside Inn"
  },
  {
    "id": "army-navy-store",
    "coordinates": [
      72.8309256,
      18.9279857
    ],
    "match": "Army And Navy Building"
  },
  {
    "id": "gateway-of-india-speedboat-ride",
    "coordinates": [
      72.8345228,
      18.9229191
    ],
    "match": "Gateway of India - Mandwa Rewas Ferry Terminal"
  },
  {
    "id": "gateway-of-india-jet-ski-slot",
    "coordinates": [
      72.8345228,
      18.9229191
    ],
    "match": "Gateway of India - Mandwa Rewas Ferry Terminal"
  },
  {
    "id": "the-taj-mahal-palace",
    "coordinates": [
      72.8330507,
      18.921902
    ],
    "match": "Taj Mahal Palace"
  },
  {
    "id": "the-oberoi-mumbai",
    "coordinates": [
      72.8324577,
      18.9284247
    ],
    "match": "Renu Oberoi"
  },
  {
    "id": "trident-nariman-point",
    "coordinates": [
      72.8210332,
      18.9276399
    ],
    "match": "Trident, Nariman-Point"
  },
  {
    "id": "hotel-diplomat",
    "coordinates": [
      72.8322344,
      18.9216884
    ],
    "match": "Hotel Diplomat"
  },
  {
    "id": "fariyas-hotel",
    "coordinates": [
      72.8300047,
      18.9170456
    ],
    "match": "Fariyas Hotel Mumbai"
  },
  {
    "id": "hotel-suba-palace",
    "coordinates": [
      72.8329689,
      18.9240096
    ],
    "match": "Hotel Suba Palace"
  },
  {
    "id": "gateway-of-india-morning-walk",
    "coordinates": [
      72.8345228,
      18.9229191
    ],
    "match": "Gateway of India - Mandwa Rewas Ferry Terminal"
  },
  {
    "id": "prince-of-wales-museum-courtyard",
    "coordinates": [
      72.8314401,
      18.9187398
    ],
    "match": "Prince Court"
  },
  {
    "id": "colaba-art-gallery-row",
    "coordinates": [
      72.8313854,
      18.9258376
    ],
    "match": "नॅशनल गॅलरी ऑफ मॉडर्न आर्ट"
  },
  {
    "id": "sassoon-docks-early-morning-walk",
    "coordinates": [
      72.8252993,
      18.9110357
    ],
    "match": "Sassoon Docks"
  },
  {
    "id": "sassoon-docks-fish-auction-viewing",
    "coordinates": [
      72.8252993,
      18.9110357
    ],
    "match": "Sassoon Docks"
  },
  {
    "id": "dhanraj-mahal-art-deco-walk",
    "coordinates": [
      72.8306139,
      18.9293596
    ],
    "match": "विक्टोरिया गोथिक और आर्ट डेका इन्सेंबल्स ऑफ़ मुंबई"
  },
  {
    "id": "afghan-church-heritage-visit",
    "coordinates": [
      72.8167686,
      18.9067788
    ],
    "match": "Afghan Church"
  },
  {
    "id": "sachivalaya-gymkhana-heritage-walk",
    "coordinates": [
      72.8265236,
      18.9259525
    ],
    "match": "Sachivalay Gymkhana"
  },
  {
    "id": "sassoon-docks-waterfront-walk",
    "coordinates": [
      72.8252993,
      18.9110357
    ],
    "match": "Sassoon Docks"
  },
  {
    "id": "girgaon-chowpatty-pav-bhaji-stalls",
    "coordinates": [
      72.8180876,
      18.955324
    ],
    "match": "Manohar Pav Bhaji"
  },
  {
    "id": "marine-drive-promenade-night-walk",
    "coordinates": [
      72.8208,
      18.9296046
    ],
    "match": "Marine Drive Promenade"
  },
  {
    "id": "oberoi-bar-nariman-point",
    "coordinates": [
      72.8235859,
      18.927089
    ],
    "match": "Nariman Point"
  },
  {
    "id": "trident-nariman-point-bar",
    "coordinates": [
      72.8210332,
      18.9276399
    ],
    "match": "Trident, Nariman-Point"
  },
  {
    "id": "nariman-point-seafront-evening",
    "coordinates": [
      72.8235859,
      18.927089
    ],
    "match": "Nariman Point"
  },
  {
    "id": "pizza-by-the-bay-night-counter",
    "coordinates": [
      72.8238813,
      18.9332945
    ],
    "match": "Pizza By The Bay"
  },
  {
    "id": "nariman-point-sunrise-run",
    "coordinates": [
      72.8235859,
      18.927089
    ],
    "match": "Nariman Point"
  },
  {
    "id": "chowpatty-garden-lounging",
    "coordinates": [
      72.8076111,
      18.9555432
    ],
    "match": "Kilachand Garden (Chowpatty Bandstand)"
  },
  {
    "id": "kamala-nehru-park-visit",
    "coordinates": [
      72.8046207,
      18.955096
    ],
    "match": "Kamala Nehru Park"
  },
  {
    "id": "hanging-gardens-visit",
    "coordinates": [
      72.8048197,
      18.9566065
    ],
    "match": "Pherozeshah Mehta Gardens (Hanging Gardens)"
  },
  {
    "id": "priyadarshini-park-ground",
    "coordinates": [
      72.7995926,
      18.9569155
    ],
    "match": "Priyadarshani Park / Shimla House"
  },
  {
    "id": "nariman-point-sunset-point",
    "coordinates": [
      72.8235859,
      18.927089
    ],
    "match": "Nariman Point"
  },
  {
    "id": "intercontinental-marine-drive",
    "coordinates": [
      72.8241417,
      18.9350805
    ],
    "match": "InterContinental Hotel"
  },
  {
    "id": "marine-drive-art-deco-heritage-stays",
    "coordinates": [
      72.8306139,
      18.9293596
    ],
    "match": "विक्टोरिया गोथिक और आर्ट डेका इन्सेंबल्स ऑफ़ मुंबई"
  },
  {
    "id": "sea-green-hotel",
    "coordinates": [
      72.8237555,
      18.9326798
    ],
    "match": "Sea Green Hotel"
  },
  {
    "id": "hotel-kemps-corner-edge-stay",
    "coordinates": [
      72.8068617,
      18.9637535
    ],
    "match": "Kemps Corner"
  },
  {
    "id": "nariman-point-business-hotels",
    "coordinates": [
      72.8235859,
      18.927089
    ],
    "match": "Nariman Point"
  },
  {
    "id": "art-deco-marine-drive-walk",
    "coordinates": [
      72.8306139,
      18.9293596
    ],
    "match": "विक्टोरिया गोथिक और आर्ट डेका इन्सेंबल्स ऑफ़ मुंबई"
  },
  {
    "id": "eros-cinema-facade-visit",
    "coordinates": [
      72.8279388,
      18.9322385
    ],
    "match": "Eros Cinema"
  },
  {
    "id": "taraporewala-aquarium-precinct-walk",
    "coordinates": [
      72.8199216,
      18.9491882
    ],
    "match": "Taraporewala Aquarium"
  },
  {
    "id": "chowpatty-sand-garden-edge",
    "coordinates": [
      72.8076111,
      18.9555432
    ],
    "match": "Kilachand Garden (Chowpatty Bandstand)"
  },
  {
    "id": "art-deco-photography-walk-class",
    "coordinates": [
      72.8306139,
      18.9293596
    ],
    "match": "विक्टोरिया गोथिक और आर्ट डेका इन्सेंबल्स ऑफ़ मुंबई"
  },
  {
    "id": "chowpatty-family-beach-evening",
    "coordinates": [
      72.8114236,
      18.9543869
    ],
    "match": "Girgaum Chowpatty Beach"
  },
  {
    "id": "vinay-health-home",
    "coordinates": [
      72.8128391,
      18.9747946
    ],
    "match": "Shetty Nursing Home (Shetty Health Services Pvt. Ltd.)"
  },
  {
    "id": "thakurdwar-shopping-street",
    "coordinates": [
      72.8236381,
      18.9500139
    ],
    "match": "Thakurdwar"
  },
  {
    "id": "girgaon-fish-market-morning",
    "coordinates": [
      72.817232,
      18.9690232
    ],
    "match": "Fish market"
  },
  {
    "id": "girgaon-chowpatty-kayaking-session",
    "coordinates": [
      72.8085624,
      18.9557637
    ],
    "match": "Chowpatty Band Stand"
  },
  {
    "id": "babulnath-temple-courtyard-rest",
    "coordinates": [
      72.8085682,
      18.958748
    ],
    "match": "Babunath Temple"
  },
  {
    "id": "girgaon-wadi-gardens",
    "coordinates": [
      72.8249634,
      18.9503008
    ],
    "match": "Navi wadi Garden"
  },
  {
    "id": "mumba-devi-temple-visit",
    "coordinates": [
      72.8307259,
      18.9519817
    ],
    "match": "Shree Mumbadevi Temple"
  },
  {
    "id": "babulnath-temple-quiet-hour",
    "coordinates": [
      72.8085682,
      18.958748
    ],
    "match": "Babunath Temple"
  },
  {
    "id": "girgaon-wadi-gardens-green-loop",
    "coordinates": [
      72.8249634,
      18.9503008
    ],
    "match": "Navi wadi Garden"
  },
  {
    "id": "babulnath-temple-green-approach",
    "coordinates": [
      72.8085682,
      18.958748
    ],
    "match": "Babunath Temple"
  },
  {
    "id": "girgaon-chowpatty-family-beach-slot",
    "coordinates": [
      72.8114236,
      18.9543869
    ],
    "match": "Girgaum Chowpatty Beach"
  },
  {
    "id": "noor-mohammadi-hotel",
    "coordinates": [
      72.8322448,
      18.9578129
    ],
    "match": "Noor Mohammadi Hotel"
  },
  {
    "id": "tawakkal-sweets",
    "coordinates": [
      72.8309033,
      18.9600922
    ],
    "match": "Tawakkal sweets"
  },
  {
    "id": "jaffer-bhais-delhi-darbar",
    "coordinates": [
      72.823385,
      18.9614573
    ],
    "match": "Delhi Darbar"
  },
  {
    "id": "mohammad-ali-road-kebab-stretch",
    "coordinates": [
      72.8343785,
      18.9518717
    ],
    "match": "Muhammad Ali Road"
  },
  {
    "id": "mohammad-ali-road-night-kebab-stretch",
    "coordinates": [
      72.8343785,
      18.9518717
    ],
    "match": "Muhammad Ali Road"
  },
  {
    "id": "noor-mohammadi-late-counter",
    "coordinates": [
      72.8322448,
      18.9578129
    ],
    "match": "Noor Mohammadi Hotel"
  },
  {
    "id": "bhendi-bazaar-perfume-shops",
    "coordinates": [
      72.8178832,
      18.96183
    ],
    "match": "Zafco Perfumes"
  },
  {
    "id": "minara-masjid-shopping-stretch",
    "coordinates": [
      72.8330818,
      18.95452
    ],
    "match": "Minara Masjid"
  },
  {
    "id": "zainab-market-bhendi",
    "coordinates": [
      72.8306604,
      18.9596452
    ],
    "match": "Zainab Manzil"
  },
  {
    "id": "mohammad-ali-road-budget-stays",
    "coordinates": [
      72.8343785,
      18.9518717
    ],
    "match": "Muhammad Ali Road"
  },
  {
    "id": "minara-masjid-lane-visit",
    "coordinates": [
      72.8330818,
      18.95452
    ],
    "match": "Minara Masjid"
  },
  {
    "id": "candies",
    "coordinates": [
      72.8298692,
      19.0495544
    ],
    "match": "Candies"
  },
  {
    "id": "pali-bhavan",
    "coordinates": [
      72.8294205,
      19.0620905
    ],
    "match": "Pali Bhavan"
  },
  {
    "id": "the-bagel-shop",
    "coordinates": [
      72.8248491,
      19.0631425
    ],
    "match": "The Bagel Shop"
  },
  {
    "id": "jai-jawan",
    "coordinates": [
      72.8346675,
      19.0642496
    ],
    "match": "Jai Jawan"
  },
  {
    "id": "carter-road-khau-galli",
    "coordinates": [
      72.822656,
      19.0705997
    ],
    "match": "Carter Road Social"
  },
  {
    "id": "yoko-sizzlers",
    "coordinates": [
      72.83473,
      19.0562679
    ],
    "match": "Yoko Sizzlers"
  },
  {
    "id": "hill-road-bakery-strip",
    "coordinates": [
      72.8241777,
      19.0526477
    ],
    "match": "Hill Road Garden"
  },
  {
    "id": "bandra-west-bar-street",
    "coordinates": [
      72.8302669,
      19.0583358
    ],
    "match": "Bandra West"
  },
  {
    "id": "the-daily-bandra",
    "coordinates": [
      72.8296379,
      19.0650907
    ],
    "match": "Ritual Daily Coffee"
  },
  {
    "id": "bonobo",
    "coordinates": [
      72.8336758,
      19.0654946
    ],
    "match": "Bonobo"
  },
  {
    "id": "bandra-hill-road-lounge-strip",
    "coordinates": [
      72.8241777,
      19.0526477
    ],
    "match": "Hill Road Garden"
  },
  {
    "id": "totos-garage",
    "coordinates": [
      72.8298004,
      19.0624858
    ],
    "match": "Toto's Garage"
  },
  {
    "id": "linking-road-shopping-street",
    "coordinates": [
      72.8342325,
      19.0655007
    ],
    "match": "Linking Road Shopping area"
  },
  {
    "id": "hill-road-shopping-strip",
    "coordinates": [
      72.8241777,
      19.0526477
    ],
    "match": "Hill Road Garden"
  },
  {
    "id": "bandra-reclamation-weekend-market",
    "coordinates": [
      72.8326014,
      19.0512275
    ],
    "match": "Bandra Reclamation"
  },
  {
    "id": "waterfield-road-boutiques",
    "coordinates": [
      72.8346902,
      19.0640656
    ],
    "match": "RK Patkar Marg (Waterfield Road)"
  },
  {
    "id": "st-paul-road-shoe-lanes",
    "coordinates": [
      72.8252243,
      19.0571775
    ],
    "match": "St. Paul Road"
  },
  {
    "id": "bandra-worli-sea-link-cycling-slot",
    "coordinates": [
      72.8267743,
      19.0442022
    ],
    "match": "Rajiv Gandhi Sea Link"
  },
  {
    "id": "bandra-bandstand-promenade",
    "coordinates": [
      72.8218606,
      19.0504556
    ],
    "match": "Bandstand"
  },
  {
    "id": "carter-road-promenade",
    "coordinates": [
      72.822656,
      19.0705997
    ],
    "match": "Carter Road Social"
  },
  {
    "id": "mount-mary-steps-walk",
    "coordinates": [
      72.8250874,
      19.0481917
    ],
    "match": "Mount Mary Steps"
  },
  {
    "id": "bandra-reclamation-evening-walk",
    "coordinates": [
      72.8326014,
      19.0512275
    ],
    "match": "Bandra Reclamation"
  },
  {
    "id": "otters-club-sit-out-bandra",
    "coordinates": [
      72.8216687,
      19.0605408
    ],
    "match": "Otters Club"
  },
  {
    "id": "taj-lands-end",
    "coordinates": [
      72.8196888,
      19.0435761
    ],
    "match": "Taj Lands End"
  },
  {
    "id": "hotel-bandra-residency",
    "coordinates": [
      72.8325298,
      19.0617235
    ],
    "match": "Grand Residency Hotel"
  },
  {
    "id": "waterfield-road-design-hostels",
    "coordinates": [
      72.8346902,
      19.0640656
    ],
    "match": "RK Patkar Marg (Waterfield Road)"
  },
  {
    "id": "bandra-west-serviced-apartments",
    "coordinates": [
      72.8260238,
      19.052135
    ],
    "match": "West View Apartments"
  },
  {
    "id": "carter-road-guesthouses",
    "coordinates": [
      72.822656,
      19.0705997
    ],
    "match": "Carter Road Social"
  },
  {
    "id": "mount-mary-basilica-visit",
    "coordinates": [
      72.8250874,
      19.0481917
    ],
    "match": "Mount Mary Steps"
  },
  {
    "id": "st-andrews-church-visit",
    "coordinates": [
      72.8258007,
      19.0547676
    ],
    "match": "St. Andrew's Church"
  },
  {
    "id": "castella-de-aguada-ruin-visit",
    "coordinates": [
      72.8184995,
      19.0419788
    ],
    "match": "Castella de Aguada"
  },
  {
    "id": "carter-road-promenade-garden-edge",
    "coordinates": [
      72.8241777,
      19.0526477
    ],
    "match": "Hill Road Garden"
  },
  {
    "id": "bandra-watercolour-class",
    "coordinates": [
      72.8340559,
      19.060126
    ],
    "match": "Water Queen"
  },
  {
    "id": "bandra-bandstand-family-evening",
    "coordinates": [
      72.8218606,
      19.0504556
    ],
    "match": "Bandstand"
  },
  {
    "id": "carter-road-family-ice-cream-walk",
    "coordinates": [
      72.8283694,
      19.074102
    ],
    "match": "Keep Kool Ice Cream & Food"
  },
  {
    "id": "bandra-family-cycling-slot",
    "coordinates": [
      72.8265298,
      19.0505565
    ],
    "match": "Breve Cycling Cafe"
  },
  {
    "id": "shiv-sagar-veg",
    "coordinates": [
      72.8461004,
      19.0981963
    ],
    "match": "Shiv Sagar Hotel"
  },
  {
    "id": "amar-juice-centre",
    "coordinates": [
      72.8369234,
      19.1093891
    ],
    "match": "Amar Juice Centre"
  },
  {
    "id": "juhu-beach-pav-bhaji-stalls",
    "coordinates": [
      72.8262132,
      19.0979952
    ],
    "match": "Rajasthan Pav Bhaji"
  },
  {
    "id": "prithvi-theatre-cafe-night",
    "coordinates": [
      72.8256355,
      19.1061914
    ],
    "match": "Prithvi Theatre"
  },
  {
    "id": "novotel-juhu-night-bar",
    "coordinates": [
      72.8242025,
      19.1087944
    ],
    "match": "Novotel Hotel"
  },
  {
    "id": "sun-n-sand-juhu-bar",
    "coordinates": [
      72.8241002,
      19.109493
    ],
    "match": "Sun-n-Sand"
  },
  {
    "id": "juhu-tara-road-weekend-stalls",
    "coordinates": [
      72.827208,
      19.0870555
    ],
    "match": "Kotak Mahindra ATM Juhu Tara road"
  },
  {
    "id": "versova-beach-lounging",
    "coordinates": [
      72.8235734,
      19.1009687
    ],
    "match": "Danda-Juhu-Versova beach walk"
  },
  {
    "id": "jw-marriott-juhu",
    "coordinates": [
      72.826037,
      19.1018231
    ],
    "match": "JW Marriott"
  },
  {
    "id": "sun-n-sand-juhu",
    "coordinates": [
      72.8241002,
      19.109493
    ],
    "match": "Sun-n-Sand"
  },
  {
    "id": "hotel-sea-princess",
    "coordinates": [
      72.8278496,
      19.0931831
    ],
    "match": "Hotel Sea Princess"
  },
  {
    "id": "ramada-plaza-juhu",
    "coordinates": [
      72.8268319,
      19.0985808
    ],
    "match": "Ramada Plaza Palm Grove"
  },
  {
    "id": "juhu-service-apartments-row",
    "coordinates": [
      72.8286869,
      19.0931749
    ],
    "match": "The Emerald Hotel And Serviced Apartments"
  },
  {
    "id": "iskcon-juhu-temple-morning",
    "coordinates": [
      72.8268798,
      19.1130667
    ],
    "match": "ISKCON Juhu Temple"
  },
  {
    "id": "prithvi-theatre-matinee-visit",
    "coordinates": [
      72.8256355,
      19.1061914
    ],
    "match": "Prithvi Theatre"
  },
  {
    "id": "juhu-family-pav-bhaji-treat",
    "coordinates": [
      72.8262132,
      19.0979952
    ],
    "match": "Rajasthan Pav Bhaji"
  },
  {
    "id": "lokhandwala-food-carts",
    "coordinates": [
      72.8246055,
      19.1430985
    ],
    "match": "Lokhandwala Complex"
  },
  {
    "id": "nom-nom-andheri",
    "coordinates": [
      72.8223454,
      19.1252302
    ],
    "match": "Nom Nom"
  },
  {
    "id": "four-bungalows-chaat-lane",
    "coordinates": [
      72.8255543,
      19.1287942
    ],
    "match": "Four Bungalows"
  },
  {
    "id": "versova-beach-cafes",
    "coordinates": [
      72.8133084,
      19.1299793
    ],
    "match": "Versova Beach"
  },
  {
    "id": "yeda-republic-andheri",
    "coordinates": [
      72.8254856,
      19.1092999
    ],
    "match": "Yeda Republic"
  },
  {
    "id": "versova-beach-night-cafes",
    "coordinates": [
      72.8133084,
      19.1299793
    ],
    "match": "Versova Beach"
  },
  {
    "id": "rise-andheri",
    "coordinates": [
      72.8285875,
      19.1388754
    ],
    "match": "Sun Rise"
  },
  {
    "id": "the-little-door-andheri",
    "coordinates": [
      72.8333522,
      19.1393909
    ],
    "match": "The Little Door"
  },
  {
    "id": "lokhandwala-market",
    "coordinates": [
      72.8246055,
      19.1430985
    ],
    "match": "Lokhandwala Complex"
  },
  {
    "id": "andheri-west-street-shopping",
    "coordinates": [
      72.8373817,
      19.136394
    ],
    "match": "Jogeshwari West"
  },
  {
    "id": "infiniti-mall-andheri",
    "coordinates": [
      72.8308659,
      19.1412176
    ],
    "match": "Infinity Mall Car Parking"
  },
  {
    "id": "four-bungalows-market",
    "coordinates": [
      72.8255543,
      19.1287942
    ],
    "match": "Four Bungalows"
  },
  {
    "id": "versova-beach-horse-riding-slot",
    "coordinates": [
      72.8133084,
      19.1299793
    ],
    "match": "Versova Beach"
  },
  {
    "id": "versova-kayaking-session",
    "coordinates": [
      72.8213871,
      19.1302777
    ],
    "match": "Versova"
  },
  {
    "id": "versova-beach-evening-sit-outs",
    "coordinates": [
      72.8133084,
      19.1299793
    ],
    "match": "Versova Beach"
  },
  {
    "id": "andheri-sports-complex",
    "coordinates": [
      72.8373653,
      19.1274759
    ],
    "match": "Andheri Sports Complex"
  },
  {
    "id": "seven-bungalow-garden-walk",
    "coordinates": [
      72.8171122,
      19.1287083
    ],
    "match": "Seven Bungalows Garden"
  },
  {
    "id": "four-bungalow-park-loop",
    "coordinates": [
      72.8255543,
      19.1287942
    ],
    "match": "Four Bungalows"
  },
  {
    "id": "andheri-west-boutique-hotels",
    "coordinates": [
      72.8274295,
      19.1011649
    ],
    "match": "Juhu Residency Boutique Hotel"
  },
  {
    "id": "lokhandwala-serviced-apartments",
    "coordinates": [
      72.8286869,
      19.0931749
    ],
    "match": "The Emerald Hotel And Serviced Apartments"
  },
  {
    "id": "versova-beach-homestays",
    "coordinates": [
      72.8133084,
      19.1299793
    ],
    "match": "Versova Beach"
  },
  {
    "id": "versova-beach-shoreline-walk",
    "coordinates": [
      72.8133084,
      19.1299793
    ],
    "match": "Versova Beach"
  },
  {
    "id": "andheri-joggers-park-green-loop",
    "coordinates": [
      72.8211666,
      19.1455869
    ],
    "match": "Chattrapati Shivaji Joggers Park"
  },
  {
    "id": "four-bungalows-seaside-garden",
    "coordinates": [
      72.8255543,
      19.1287942
    ],
    "match": "Four Bungalows"
  },
  {
    "id": "versova-beach-family-evening",
    "coordinates": [
      72.8133084,
      19.1299793
    ],
    "match": "Versova Beach"
  },
  {
    "id": "lokhandwala-family-garden-slot",
    "coordinates": [
      72.8269168,
      19.145163
    ],
    "match": "Lokhandwala Garden"
  },
  {
    "id": "versova-family-fishing-village-walk",
    "coordinates": [
      72.8060957,
      19.1384723
    ],
    "match": "BMC Versova Village Sewage Water Pumping Station"
  },
  {
    "id": "hiranandani-gardens-cafe-strip",
    "coordinates": [
      72.9151649,
      19.1299491
    ],
    "match": "Gulmohar Garden Cafe"
  },
  {
    "id": "central-avenue-bakeries",
    "coordinates": [
      72.9124779,
      19.1205304
    ],
    "match": "Central Avenue"
  },
  {
    "id": "powai-lakefront-evening-walk",
    "coordinates": [
      72.913808,
      19.129091
    ],
    "match": "Guest House Lakefront"
  },
  {
    "id": "the-chase-rooftop-powai",
    "coordinates": [
      72.9089422,
      19.1161139
    ],
    "match": "JP Morgan Chase"
  },
  {
    "id": "galleria-market",
    "coordinates": [
      72.911416,
      19.1189565
    ],
    "match": "Gelleria Optics"
  },
  {
    "id": "central-avenue-shops",
    "coordinates": [
      72.9124779,
      19.1205304
    ],
    "match": "Central Avenue"
  },
  {
    "id": "powai-vihar-lake-walk",
    "coordinates": [
      72.8982965,
      19.1397456
    ],
    "match": "Vihar Lake"
  },
  {
    "id": "hiranandani-gardens-stroll",
    "coordinates": [
      72.911464,
      19.1183882
    ],
    "match": "Hiranandani Gardens"
  },
  {
    "id": "nirvana-park-visit",
    "coordinates": [
      72.9118156,
      19.122422
    ],
    "match": "Nirvana Park"
  },
  {
    "id": "powai-lakeside-yoga-slot",
    "coordinates": [
      72.9145698,
      19.1285732
    ],
    "match": "Lakeside Road"
  },
  {
    "id": "the-lalit-mumbai-powai",
    "coordinates": [
      72.8757789,
      19.1054069
    ],
    "match": "Lalit Mumbai"
  },
  {
    "id": "meluha-the-fern-powai",
    "coordinates": [
      72.9109596,
      19.11783
    ],
    "match": "Meluha The Fern"
  },
  {
    "id": "hotel-powai-inn",
    "coordinates": [
      72.8800918,
      19.1177459
    ],
    "match": "Hotel Grand Inn"
  },
  {
    "id": "rodas-an-ecotel-hotel",
    "coordinates": [
      72.9116829,
      19.1185925
    ],
    "match": "Rodas - An Ecotel Hotel"
  },
  {
    "id": "iit-bombay-heritage-buildings-walk",
    "coordinates": [
      72.913191,
      19.1357052
    ],
    "match": "small swimming pool"
  },
  {
    "id": "iit-bombay-green-trail-edge",
    "coordinates": [
      72.913191,
      19.1357052
    ],
    "match": "small swimming pool"
  },
  {
    "id": "powai-lakeside-promenade-south-bank",
    "coordinates": [
      72.9168507,
      19.1241767
    ],
    "match": "South Indian Bank"
  },
  {
    "id": "powai-lakeside-family-evening",
    "coordinates": [
      72.9145698,
      19.1285732
    ],
    "match": "Lakeside Road"
  },
  {
    "id": "aarey-milk-colony-trail-network",
    "coordinates": [
      72.8707223,
      19.1561292
    ],
    "match": "Aarey Milk Colony"
  },
  {
    "id": "aarey-milk-colony-shady-lanes",
    "coordinates": [
      72.8707223,
      19.1561292
    ],
    "match": "Aarey Milk Colony"
  },
  {
    "id": "aarey-family-picnic-meadow",
    "coordinates": [
      72.8552553,
      19.1465009
    ],
    "match": "silver meadows"
  },
  {
    "id": "aarey-family-dairy-visit",
    "coordinates": [
      72.8781166,
      19.1301529
    ],
    "match": "Pavitra Dairy Farm"
  },
  {
    "id": "aarey-family-nature-trail",
    "coordinates": [
      72.8927327,
      19.1627003
    ],
    "match": "BNHS Nature Reserve"
  },
  {
    "id": "shivaji-park-chaat-stalls",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "aram-vada-pav-stall-dadar-tt",
    "coordinates": [
      72.8313766,
      19.0205197
    ],
    "match": "Ashok Vada Pav"
  },
  {
    "id": "dadar-market-misal-counters",
    "coordinates": [
      72.8424101,
      19.0223451
    ],
    "match": "House Of Misal"
  },
  {
    "id": "shivaji-park-evening-walk-circuit",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "dadar-tt-clothing-lanes",
    "coordinates": [
      72.8375969,
      18.9970883
    ],
    "match": "Hype clothing"
  },
  {
    "id": "dadar-vegetable-market",
    "coordinates": [
      72.8558741,
      19.0276818
    ],
    "match": "Vikas Vegetable"
  },
  {
    "id": "shivaji-park-sports-shops",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "plaza-cinema-junction-stalls-dadar",
    "coordinates": [
      72.842855,
      19.0219225
    ],
    "match": "Plaza Cinema"
  },
  {
    "id": "shivaji-park-running-loop",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "five-gardens-morning-run",
    "coordinates": [
      72.8538406,
      19.0201251
    ],
    "match": "Garden E, Five Gardens"
  },
  {
    "id": "shivaji-park-lounging",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "five-gardens-outing",
    "coordinates": [
      72.8538406,
      19.0201251
    ],
    "match": "Garden E, Five Gardens"
  },
  {
    "id": "portuguese-church-garden-rest",
    "coordinates": [
      72.8364514,
      19.0186203
    ],
    "match": "Portuguese Church"
  },
  {
    "id": "shivaji-park-memorial-circuit",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "dadar-parsi-colony-heritage-walk",
    "coordinates": [
      72.8427072,
      19.0425635
    ],
    "match": "Mahim Parsi Colony"
  },
  {
    "id": "portuguese-church-visit-dadar",
    "coordinates": [
      72.8364514,
      19.0186203
    ],
    "match": "Portuguese Church"
  },
  {
    "id": "shivaji-park-green-loop",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "five-gardens-canopy-walk",
    "coordinates": [
      72.8538406,
      19.0201251
    ],
    "match": "Garden E, Five Gardens"
  },
  {
    "id": "shivaji-park-sea-face-morning-walk",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "five-gardens-family-evening",
    "coordinates": [
      72.8538406,
      19.0201251
    ],
    "match": "Garden E, Five Gardens"
  },
  {
    "id": "shivaji-park-family-play-slot",
    "coordinates": [
      72.8391613,
      19.0287453
    ],
    "match": "Shivaji Park"
  },
  {
    "id": "cafe-madras",
    "coordinates": [
      72.8550473,
      19.0276726
    ],
    "match": "Cafe Madras"
  },
  {
    "id": "cafe-mysore",
    "coordinates": [
      72.8554829,
      19.0275709
    ],
    "match": "Cafe Mysore"
  },
  {
    "id": "ram-ashraya",
    "coordinates": [
      72.8517121,
      19.0280158
    ],
    "match": "Ram Ashray South Indian"
  },
  {
    "id": "b-merwan-co",
    "coordinates": [
      72.8394706,
      19.0014915
    ],
    "match": "Aimai Merwanji Street"
  },
  {
    "id": "a-rama-nayaks-udipi-shri-krishna-boarding",
    "coordinates": [
      72.850662,
      19.0273999
    ],
    "match": "A Rama Nayak's Shrikrishna Boarding"
  },
  {
    "id": "kings-circle-chaat-carts",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "kings-circle-night-chaat-carts",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "kings-circle-shopping-strip",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "matunga-east-vegetable-market",
    "coordinates": [
      72.8558741,
      19.0276818
    ],
    "match": "Vikas Vegetable"
  },
  {
    "id": "king-circle-fitness-walk",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "king-circle-garden",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "five-gardens-tai-chi-slot",
    "coordinates": [
      72.8538406,
      19.0201251
    ],
    "match": "Garden E, Five Gardens"
  },
  {
    "id": "matunga-south-indian-boarder-lodges",
    "coordinates": [
      72.8517121,
      19.0280158
    ],
    "match": "Ram Ashray South Indian"
  },
  {
    "id": "king-circle-budget-hotels",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "south-indian-community-heritage-walk-matunga",
    "coordinates": [
      72.8517121,
      19.0280158
    ],
    "match": "Ram Ashray South Indian"
  },
  {
    "id": "king-circle-banyan-corner",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "matunga-south-indian-cooking-class",
    "coordinates": [
      72.8517121,
      19.0280158
    ],
    "match": "Ram Ashray South Indian"
  },
  {
    "id": "king-circle-family-garden-slot",
    "coordinates": [
      72.8577375,
      19.0316822
    ],
    "match": "King's Circle"
  },
  {
    "id": "matunga-family-cycling-slot",
    "coordinates": [
      72.8265298,
      19.0505565
    ],
    "match": "Breve Cycling Cafe"
  },
  {
    "id": "itc-grand-central-dining",
    "coordinates": [
      72.8382792,
      18.9982254
    ],
    "match": "ITC Grand Central"
  },
  {
    "id": "slink-bardot",
    "coordinates": [
      72.8175515,
      19.0169864
    ],
    "match": "Slink & Bardot"
  },
  {
    "id": "four-seasons-hotel-bar",
    "coordinates": [
      72.8203935,
      18.994204
    ],
    "match": "Four Seasons Hotel"
  },
  {
    "id": "aer-at-four-seasons",
    "coordinates": [
      72.8203935,
      18.994204
    ],
    "match": "Four Seasons Hotel"
  },
  {
    "id": "tote-on-the-turf",
    "coordinates": [
      72.8232049,
      18.9819716
    ],
    "match": "Tote on the Turf"
  },
  {
    "id": "worli-sea-face-saturday-market",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "mathuradas-mill-compound-shops",
    "coordinates": [
      72.8466022,
      19.0119707
    ],
    "match": "Kohinoor Mill Compound"
  },
  {
    "id": "mahalaxmi-racecourse-running-loop",
    "coordinates": [
      72.819762,
      18.9851816
    ],
    "match": "Mahalaxmi Racecourse"
  },
  {
    "id": "worli-bandra-sea-link-run-slot",
    "coordinates": [
      72.8143707,
      19.0145815
    ],
    "match": "Rajiv Gandhi Sea Link"
  },
  {
    "id": "lower-parel-business-park-gardens",
    "coordinates": [
      72.829155,
      18.9990011
    ],
    "match": "Peninsula Business Park"
  },
  {
    "id": "worli-sea-face-morning-yoga",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "itc-grand-central-parel",
    "coordinates": [
      72.8382792,
      18.9982254
    ],
    "match": "ITC Grand Central"
  },
  {
    "id": "worli-sea-face-premium-stays",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "phoenix-mills-chimney-heritage-stop",
    "coordinates": [
      72.8234944,
      18.9950885
    ],
    "match": "Phoenix Mills Parking Lot"
  },
  {
    "id": "lower-parel-business-park-green-loop",
    "coordinates": [
      72.829155,
      18.9990011
    ],
    "match": "Peninsula Business Park"
  },
  {
    "id": "palladium-family-play-zone",
    "coordinates": [
      72.8236906,
      18.9953247
    ],
    "match": "Palladium West Zone"
  },
  {
    "id": "rivali-park-retail-strip",
    "coordinates": [
      72.8656993,
      19.2169357
    ],
    "match": "Rivali Park Road"
  },
  {
    "id": "kanheri-caves-trek-inside-sgnp",
    "coordinates": [
      72.8947398,
      19.2144265
    ],
    "match": "Kanheri Caves Road"
  },
  {
    "id": "sgnp-lion-safari-viewing",
    "coordinates": [
      72.8884927,
      19.2418107
    ],
    "match": "Lion Safari Road"
  },
  {
    "id": "kanheri-caves-heritage-extension",
    "coordinates": [
      72.8947398,
      19.2144265
    ],
    "match": "Kanheri Caves Road"
  },
  {
    "id": "sgnp-lion-safari-family-slot",
    "coordinates": [
      72.8884927,
      19.2418107
    ],
    "match": "Lion Safari Road"
  },
  {
    "id": "sgnp-family-nature-trail",
    "coordinates": [
      72.8728884,
      19.2123321
    ],
    "match": "Nature's Basket"
  },
  {
    "id": "palm-beach-road-cafes",
    "coordinates": [
      73.0050477,
      19.0551885
    ],
    "match": "Palm Beach Service Road"
  },
  {
    "id": "palm-beach-galleria-evening-strip",
    "coordinates": [
      73.0077005,
      19.0850238
    ],
    "match": "Palm Beach Galleria Mall"
  },
  {
    "id": "palm-beach-night-cafe-strip-vashi",
    "coordinates": [
      73.0016203,
      19.0640394
    ],
    "match": "Palm Beach Marg"
  },
  {
    "id": "inorbit-mall-vashi",
    "coordinates": [
      72.9999608,
      19.0643025
    ],
    "match": "इनॉर्बिट मॉल"
  },
  {
    "id": "sector-17-market-vashi",
    "coordinates": [
      73.0040067,
      19.1021224
    ],
    "match": "Gulabson's"
  },
  {
    "id": "palm-beach-galleria",
    "coordinates": [
      73.0077005,
      19.0850238
    ],
    "match": "Palm Beach Galleria Mall"
  },
  {
    "id": "vashi-creek-kayaking-slot",
    "coordinates": [
      72.9950517,
      19.0762501
    ],
    "match": "Creek View"
  },
  {
    "id": "vashi-cycling-loop-palm-beach",
    "coordinates": [
      73.0016203,
      19.0640394
    ],
    "match": "Palm Beach Marg"
  },
  {
    "id": "vashi-mini-seashore-paddle-session",
    "coordinates": [
      72.9929328,
      19.0817346
    ],
    "match": "mini seashore"
  },
  {
    "id": "vashi-mini-seashore-park",
    "coordinates": [
      72.9929328,
      19.0817346
    ],
    "match": "mini seashore"
  },
  {
    "id": "palm-beach-evening-benches",
    "coordinates": [
      73.0016203,
      19.0640394
    ],
    "match": "Palm Beach Marg"
  },
  {
    "id": "palm-beach-vashi-business-hotels",
    "coordinates": [
      73.0016203,
      19.0640394
    ],
    "match": "Palm Beach Marg"
  },
  {
    "id": "st-marys-church-vashi-visit",
    "coordinates": [
      72.9953201,
      19.0820142
    ],
    "match": "St. Mary's Junior College"
  },
  {
    "id": "vashi-mini-seashore-walk-extension",
    "coordinates": [
      72.9929328,
      19.0817346
    ],
    "match": "mini seashore"
  },
  {
    "id": "palm-beach-shoreline-walk",
    "coordinates": [
      73.0016203,
      19.0640394
    ],
    "match": "Palm Beach Marg"
  },
  {
    "id": "vashi-mini-seashore-family-evening",
    "coordinates": [
      72.9929328,
      19.0817346
    ],
    "match": "mini seashore"
  },
  {
    "id": "palm-beach-family-ice-cream-walk",
    "coordinates": [
      73.0016203,
      19.0640394
    ],
    "match": "Palm Beach Marg"
  },
  {
    "id": "seawoods-grand-central-food-court",
    "coordinates": [
      73.0187243,
      19.0209279
    ],
    "match": "Seawoods Grand Central Tower 2"
  },
  {
    "id": "wonders-park-snack-carts",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "seawoods-grand-central-late-food-court",
    "coordinates": [
      73.0187243,
      19.0209279
    ],
    "match": "Seawoods Grand Central Tower 2"
  },
  {
    "id": "wonders-park-evening-lights-walk",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "seawoods-grand-central-retail",
    "coordinates": [
      73.0187243,
      19.0209279
    ],
    "match": "Seawoods Grand Central Tower 2"
  },
  {
    "id": "wonders-park-vendor-carts",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "wonders-park-climbing-wall",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "wonders-park-family-outing",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "seawoods-grand-central-area-hotels",
    "coordinates": [
      73.0328131,
      19.0105342
    ],
    "match": "Hotel Grande51"
  },
  {
    "id": "nerul-balaji-temple-visit",
    "coordinates": [
      73.0142261,
      19.0324262
    ],
    "match": "Balaji Temple"
  },
  {
    "id": "wonders-park-green-lawns-walk",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "seawoods-grand-central-mangrove-edge",
    "coordinates": [
      73.0187243,
      19.0209279
    ],
    "match": "Seawoods Grand Central Tower 2"
  },
  {
    "id": "wonders-park-nerul-family-evening",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "wonders-park-mini-train-ride",
    "coordinates": [
      73.0259807,
      19.0251233
    ],
    "match": "Wonders Park"
  },
  {
    "id": "belapur-creek-kayaking",
    "coordinates": [
      73.0379342,
      19.006541
    ],
    "match": "Panvel Creek"
  },
  {
    "id": "belapur-parsik-hill-ridge-walk",
    "coordinates": [
      73.0291933,
      19.0225814
    ],
    "match": "Parsik Hill Viewpoint"
  },
  {
    "id": "cbd-belapur-central-gardens",
    "coordinates": [
      73.0391304,
      19.0190075
    ],
    "match": "CBD Belapur"
  },
  {
    "id": "hotel-sahara-star-equivalent-belapur",
    "coordinates": [
      73.0406707,
      19.0154642
    ],
    "match": "K Star Hotel"
  },
  {
    "id": "belapur-creek-edge-walk",
    "coordinates": [
      73.0379342,
      19.006541
    ],
    "match": "Panvel Creek"
  },
  {
    "id": "belapur-fort-green-trail",
    "coordinates": [
      73.0356556,
      19.036369
    ],
    "match": "Green Valley Park"
  },
  {
    "id": "belapur-watercolour-weekend-class",
    "coordinates": [
      73.0148531,
      19.0068672
    ],
    "match": "Water Well"
  },
  {
    "id": "utsav-chowk-snack-counters",
    "coordinates": [
      73.0589404,
      19.0326108
    ],
    "match": "Utsav Chowk"
  },
  {
    "id": "little-world-food-court",
    "coordinates": [
      73.0664402,
      19.0306929
    ],
    "match": "Little World Mall"
  },
  {
    "id": "central-park-evening-food-carts",
    "coordinates": [
      73.0759837,
      19.0536797
    ],
    "match": "Central Park"
  },
  {
    "id": "utsav-chowk-night-promenade",
    "coordinates": [
      73.0589404,
      19.0326108
    ],
    "match": "Utsav Chowk"
  },
  {
    "id": "central-park-kharghar-evening-lights",
    "coordinates": [
      73.0759837,
      19.0536797
    ],
    "match": "Central Park"
  },
  {
    "id": "little-world-late-food-court",
    "coordinates": [
      73.0664402,
      19.0306929
    ],
    "match": "Little World Mall"
  },
  {
    "id": "utsav-chowk-night-chai-stalls",
    "coordinates": [
      73.0589404,
      19.0326108
    ],
    "match": "Utsav Chowk"
  },
  {
    "id": "little-world-mall",
    "coordinates": [
      73.0664402,
      19.0306929
    ],
    "match": "Little World Mall"
  },
  {
    "id": "utsav-chowk-bazaar-stalls",
    "coordinates": [
      73.0589404,
      19.0326108
    ],
    "match": "Utsav Chowk"
  },
  {
    "id": "central-park-vendor-rows",
    "coordinates": [
      73.0759837,
      19.0536797
    ],
    "match": "Central Park"
  },
  {
    "id": "kharghar-waterfall-monsoon-hike",
    "coordinates": [
      73.0405374,
      19.0410722
    ],
    "match": "Belapur Waterfalls"
  },
  {
    "id": "kharghar-valley-trail-run",
    "coordinates": [
      73.0765227,
      19.0753536
    ],
    "match": "Valley Shilp Road"
  },
  {
    "id": "central-park-cycling-loop",
    "coordinates": [
      73.0759837,
      19.0536797
    ],
    "match": "Central Park"
  },
  {
    "id": "central-park-kharghar-picnic-lawns",
    "coordinates": [
      73.0759837,
      19.0536797
    ],
    "match": "Central Park"
  },
  {
    "id": "utsav-chowk-evening-promenade",
    "coordinates": [
      73.0589404,
      19.0326108
    ],
    "match": "Utsav Chowk"
  },
  {
    "id": "central-park-adjacent-stays",
    "coordinates": [
      73.0759837,
      19.0536797
    ],
    "match": "Central Park"
  },
  {
    "id": "central-park-kharghar-green-loop",
    "coordinates": [
      73.0759837,
      19.0536797
    ],
    "match": "Central Park"
  },
  {
    "id": "kharghar-watercolour-class",
    "coordinates": [
      73.0702648,
      19.0365104
    ],
    "match": "Kharghar Water Station"
  },
  {
    "id": "central-park-kharghar-family-picnic",
    "coordinates": [
      73.0759837,
      19.0536797
    ],
    "match": "Central Park"
  },
  {
    "id": "central-park-toy-train-ride",
    "coordinates": [
      73.0759837,
      19.0536797
    ],
    "match": "Central Park"
  },
  {
    "id": "little-world-mall-family-zone",
    "coordinates": [
      73.0664402,
      19.0306929
    ],
    "match": "Little World Mall"
  },
  {
    "id": "kharghar-valley-boating-slot",
    "coordinates": [
      73.0765227,
      19.0753536
    ],
    "match": "Valley Shilp Road"
  },
  {
    "id": "airoli-creek-kayaking",
    "coordinates": [
      72.9911904,
      19.1727986
    ],
    "match": "Thane Creek"
  },
  {
    "id": "airoli-knowledge-park-garden",
    "coordinates": [
      72.9903341,
      19.1787757
    ],
    "match": "Capgemini Knowledge Park"
  },
  {
    "id": "airoli-corporate-stays",
    "coordinates": [
      73.0127197,
      19.1272774
    ],
    "match": "Reliance Corporate Park"
  },
  {
    "id": "airoli-knowledge-park-green-belt",
    "coordinates": [
      72.9903341,
      19.1787757
    ],
    "match": "Capgemini Knowledge Park"
  },
  {
    "id": "airoli-watercolour-class",
    "coordinates": [
      72.9874767,
      19.1503286
    ],
    "match": "Signia Water Front"
  },
  {
    "id": "airoli-knowledge-park-family-walk",
    "coordinates": [
      72.9903341,
      19.1787757
    ],
    "match": "Capgemini Knowledge Park"
  },
  {
    "id": "airoli-creek-family-evening",
    "coordinates": [
      72.9911904,
      19.1727986
    ],
    "match": "Thane Creek"
  },
  {
    "id": "panvel-station-khau-galli",
    "coordinates": [
      73.1243133,
      18.9948017
    ],
    "match": "Khau Galli"
  },
  {
    "id": "panvel-station-late-khau-galli",
    "coordinates": [
      73.1243133,
      18.9948017
    ],
    "match": "Khau Galli"
  },
  {
    "id": "worli-sea-face-evening-food-carts",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "worli-sea-face-cycling-loop",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "worli-sea-face-promenade",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "worli-fort-courtyard",
    "coordinates": [
      72.8143166,
      18.9867462
    ],
    "match": "Lotus Court"
  },
  {
    "id": "worli-sea-link-view-hotels",
    "coordinates": [
      72.8143707,
      19.0145815
    ],
    "match": "Rajiv Gandhi Sea Link"
  },
  {
    "id": "haji-ali-causeway-walk",
    "coordinates": [
      72.8093021,
      18.981245
    ],
    "match": "Haji Ali Causeway"
  },
  {
    "id": "worli-sea-face-breeze-walk",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "worli-fort-coastal-edge",
    "coordinates": [
      72.8116654,
      18.9929883
    ],
    "match": "Mumbai Coastal Road"
  },
  {
    "id": "worli-sea-face-banyan-corner",
    "coordinates": [
      72.8180858,
      19.0164197
    ],
    "match": "Sea Corner"
  },
  {
    "id": "worli-photography-walk-class",
    "coordinates": [
      72.8358536,
      19.0180755
    ],
    "match": "Vineye Photo School"
  },
  {
    "id": "worli-sea-face-family-evening-walk",
    "coordinates": [
      72.8153817,
      19.010022
    ],
    "match": "Khan Abdul Gaffar Khan Marg"
  },
  {
    "id": "malabar-hill-perimeter-walk",
    "coordinates": [
      72.8044801,
      18.9554402
    ],
    "match": "Malabar Hill Post Office"
  },
  {
    "id": "kamala-nehru-park-fitness-loop",
    "coordinates": [
      72.8046207,
      18.955096
    ],
    "match": "Kamala Nehru Park"
  },
  {
    "id": "walkeshwar-ridge-walk",
    "coordinates": [
      72.7965343,
      18.9481893
    ],
    "match": "South Ridge"
  },
  {
    "id": "kamala-nehru-park-morning-walk",
    "coordinates": [
      72.8046207,
      18.955096
    ],
    "match": "Kamala Nehru Park"
  },
  {
    "id": "hanging-gardens-terrace-loop",
    "coordinates": [
      72.8048197,
      18.9566065
    ],
    "match": "Pherozeshah Mehta Gardens (Hanging Gardens)"
  },
  {
    "id": "malabar-hill-viewpoint-garden",
    "coordinates": [
      72.8044801,
      18.9554402
    ],
    "match": "Malabar Hill Post Office"
  },
  {
    "id": "malabar-hill-boutique-stays",
    "coordinates": [
      72.8044801,
      18.9554402
    ],
    "match": "Malabar Hill Post Office"
  },
  {
    "id": "ridge-road-premium-apartments-stays",
    "coordinates": [
      72.8063957,
      18.9578237
    ],
    "match": "B G Kher Marg (Ridge Road)"
  },
  {
    "id": "babulnath-temple-extension-visit",
    "coordinates": [
      72.8085682,
      18.958748
    ],
    "match": "Babunath Temple"
  },
  {
    "id": "hanging-gardens-canopy-walk",
    "coordinates": [
      72.8048197,
      18.9566065
    ],
    "match": "Pherozeshah Mehta Gardens (Hanging Gardens)"
  },
  {
    "id": "kamala-nehru-park-hedge-loops",
    "coordinates": [
      72.8046207,
      18.955096
    ],
    "match": "Kamala Nehru Park"
  },
  {
    "id": "malabar-hill-ridge-green-walk",
    "coordinates": [
      72.8044801,
      18.9554402
    ],
    "match": "Malabar Hill Post Office"
  },
  {
    "id": "hanging-gardens-sunset-viewpoint-lawn",
    "coordinates": [
      72.8048197,
      18.9566065
    ],
    "match": "Pherozeshah Mehta Gardens (Hanging Gardens)"
  },
  {
    "id": "kamala-nehru-park-family-playground",
    "coordinates": [
      72.8046207,
      18.955096
    ],
    "match": "Kamala Nehru Park"
  },
  {
    "id": "hanging-gardens-family-picnic",
    "coordinates": [
      72.8048197,
      18.9566065
    ],
    "match": "Pherozeshah Mehta Gardens (Hanging Gardens)"
  },
  {
    "id": "malabar-hill-family-sunset-slot",
    "coordinates": [
      72.8044801,
      18.9554402
    ],
    "match": "Malabar Hill Post Office"
  },
  {
    "id": "sewri-flamingo-point-jetty-approach",
    "coordinates": [
      72.8615436,
      18.9956242
    ],
    "match": "Flamingo Point"
  },
  {
    "id": "cream-centre",
    "coordinates": [
      72.8133136,
      18.955594
    ],
    "match": "Cream Centre, Marine Drive"
  },
  {
    "id": "hearsch-bakery",
    "coordinates": [
      72.8269905,
      19.0551689
    ],
    "match": "J Hearsch and Co, Hill Road"
  },
  {
    "id": "aaswad",
    "coordinates": [
      72.8405857,
      19.0256504
    ],
    "match": "Aaswad, Lady Jamshedji Road"
  },
  {
    "id": "palladium-mall",
    "coordinates": [
      72.8241403,
      18.9941708
    ],
    "match": "Palladium, 462"
  },
  {
    "id": "sewri-market-morning",
    "coordinates": [
      72.8494932,
      18.9991592
    ],
    "match": "Sewri Fish Market, Acharya Donde Marg"
  },
  {
    "id": "vashi-market",
    "coordinates": [
      72.9947957,
      19.070306
    ],
    "match": "Shree Ganesh Kripa Vegetable Market, Vashi"
  },
  {
    "id": "airoli-market",
    "coordinates": [
      72.9929369,
      19.1435335
    ],
    "match": "Local Market, Rama Gosavi Marg"
  },
  {
    "id": "panvel-old-market",
    "coordinates": [
      73.1096429,
      18.9862373
    ],
    "match": "Old Panvel Bhaji Market, New Panvel"
  },
  {
    "id": "kharghar-hills-trek",
    "coordinates": [
      73.0613956,
      19.0725644
    ],
    "match": "Khargar Hills Viewpoint Trail, Owe Camp"
  },
  {
    "id": "kharghar-hills-sunrise-hike",
    "coordinates": [
      73.0613956,
      19.0725644
    ],
    "match": "Khargar Hills Viewpoint Trail, Owe Camp"
  }
];
