// Generated by scripts/verify-media.mjs - do not edit by hand.
// Every entry was verified against its live source at generation time.
export type GeneratedImage = { key: string; file: string; credit: string; query: string };

export const generatedImages: GeneratedImage[] = [
  {
    "key": "commons-0",
    "file": "File:Kala Ghoda.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Fort Kala Ghoda"
  },
  {
    "key": "commons-1",
    "file": "File:Kala Ghoda, Fort, Mumbai, Maharashtra 400001, India - panoramio.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Fort Kala Ghoda"
  },
  {
    "key": "commons-2",
    "file": "File:MumbaiBrickCart gobeirne.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Colaba Causeway"
  },
  {
    "key": "commons-3",
    "file": "File:MumbaiIceCart gobeirne.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Colaba Causeway"
  },
  {
    "key": "commons-4",
    "file": "File:Mumbai 03-2016 27 skyline at Marine Drive.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Marine Drive Mumbai"
  },
  {
    "key": "commons-5",
    "file": "File:Mumbai 03-2016 46 evening at Marine Drive.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Marine Drive Mumbai"
  },
  {
    "key": "commons-6",
    "file": "File:Bhindi Bazaar.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Bhendi Bazaar Mumbai"
  },
  {
    "key": "commons-7",
    "file": "File:Old bhendi Bazaar.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Bhendi Bazaar Mumbai"
  },
  {
    "key": "commons-8",
    "file": "File:Lesser Flamingos at Sewri Mudflats, Mumbai by Raju Kasambe.JPG",
    "credit": "Wikimedia Commons contributor",
    "query": "Sewri Mumbai"
  },
  {
    "key": "commons-9",
    "file": "File:Mumbai 03-2016 56 Sewri station.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Sewri Mumbai"
  },
  {
    "key": "commons-39",
    "file": "File:Colaba Causeway,Mumbai - panoramio.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Colaba Causeway"
  },
  {
    "key": "commons-40",
    "file": "File:Marine Drive at Night.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Marine Drive Mumbai"
  },
  {
    "key": "commons-41",
    "file": "File:Marine Drive Mumbai.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Marine Drive Mumbai"
  },
  {
    "key": "commons-42",
    "file": "File:Palm Beach Road 1.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Navi Mumbai Palm Beach Road"
  },
  {
    "key": "commons-43",
    "file": "File:Palm Beach Road 2.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Navi Mumbai Palm Beach Road"
  },
  {
    "key": "commons-44",
    "file": "File:Mumbai Skyline at Night.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai skyline"
  },
  {
    "key": "commons-45",
    "file": "File:Mumbai 03-2016 09 skyline of Lotus Colony.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai skyline"
  },
  {
    "key": "commons-46",
    "file": "File:Mumbai Train.JPG",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai local train"
  },
  {
    "key": "commons-47",
    "file": "File:Mumbai suburban railway emu 1.JPG",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai local train"
  },
  {
    "key": "commons-48",
    "file": "File:KalaGhoda, Fort,Mumbai - panoramio (26).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Fort Kala Ghoda"
  },
  {
    "key": "commons-49",
    "file": "File:KalaGhoda, Fort,Mumbai - panoramio (32).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Fort Kala Ghoda"
  },
  {
    "key": "commons-21",
    "file": "File:Kala Ghoda, Fort, Mumbai, Maharashtra 400001, India - panoramio (1).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Fort Kala Ghoda"
  },
  {
    "key": "commons-22",
    "file": "File:Kala Ghoda, Fort, Mumbai, Maharashtra 400001, India - panoramio (2).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Fort Kala Ghoda"
  },
  {
    "key": "commons-23",
    "file": "File:Antiques being sold on Colaba Causeway.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Colaba Causeway"
  },
  {
    "key": "commons-24",
    "file": "File:Colaba Causeway construction, view from Colaba island, 1826.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Colaba Causeway"
  },
  {
    "key": "commons-25",
    "file": "File:Marine Drive in Mumbai 20.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Marine Drive Mumbai"
  },
  {
    "key": "commons-26",
    "file": "File:Marine Lines Mumbai 2021.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Marine Drive Mumbai"
  },
  {
    "key": "commons-27",
    "file": "File:Kala Ghoda, Fort, Mumbai, Maharashtra 400001, India - panoramio (3).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Fort Kala Ghoda"
  },
  {
    "key": "commons-28",
    "file": "File:Kala Ghoda, Fort, Mumbai, Maharashtra 400001, India - panoramio (4).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Fort Kala Ghoda"
  },
  {
    "key": "commons-29",
    "file": "File:Bagdadi Restaurant, Colaba, Mumbai.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Colaba Causeway"
  },
  {
    "key": "commons-30",
    "file": "File:Colaba Causeway - panoramio (2).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Colaba Causeway"
  },
  {
    "key": "commons-31",
    "file": "File:Marine Drive of Mumbai.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Marine Drive Mumbai"
  },
  {
    "key": "commons-32",
    "file": "File:SWITCH - Ac Double Decker Bus of BEST, Marine Drive Mumbai.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Marine Drive Mumbai"
  },
  {
    "key": "commons-33",
    "file": "File:Girgaum Chowpatty.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Girgaon Chowpatty Mumbai"
  },
  {
    "key": "commons-34",
    "file": "File:Girgaum Chowpatty Sea.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Girgaon Chowpatty Mumbai"
  },
  {
    "key": "commons-35",
    "file": "File:Navi Mumbai India.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Belapur Navi Mumbai"
  },
  {
    "key": "commons-36",
    "file": "File:Palm Beach Road, Belapur, Navi Mumbai.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Belapur Navi Mumbai"
  },
  {
    "key": "commons-37",
    "file": "File:Utsav Chauk, Kharghar Navi Mumbai.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Kharghar Navi Mumbai"
  },
  {
    "key": "commons-38",
    "file": "File:Central Park, Kharghar, Navi Mumbai, India.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Kharghar Navi Mumbai"
  },
  {
    "key": "commons-39",
    "file": "File:Little Cormorant, Airoli, Navi Mumbai, Maharashtra 2.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Airoli Navi Mumbai"
  },
  {
    "key": "commons-40",
    "file": "File:Little Cormorant, Airoli, Navi Mumbai, Maharashtra 1.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Airoli Navi Mumbai"
  },
  {
    "key": "commons-41",
    "file": "File:Dhodani,Panvel,Maharashtra - panoramio (2).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Panvel Maharashtra"
  },
  {
    "key": "commons-42",
    "file": "File:Dhodani,Panvel,Maharashtra - panoramio (16).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Panvel Maharashtra"
  },
  {
    "key": "commons-43",
    "file": "File:Kala Ghoda, Fort, Mumbai, Maharashtra 400001, India - panoramio (5).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Fort Kala Ghoda"
  },
  {
    "key": "commons-44",
    "file": "File:KalaGhoda, Fort,Mumbai - panoramio.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Fort Kala Ghoda"
  },
  {
    "key": "commons-45",
    "file": "File:Bheed Bhanjan Mahadev Mandir in Colaba, Mumbai.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Colaba Causeway"
  },
  {
    "key": "commons-46",
    "file": "File:Colaba Causeway,Mumbai - panoramio (1).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Colaba Causeway"
  },
  {
    "key": "commons-47",
    "file": "File:Marine Drive Mumbai 2.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Marine Drive Mumbai"
  },
  {
    "key": "commons-48",
    "file": "File:Taj Hotel Mumbai Marine Drive Photo by Chirag Lad.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Marine Drive Mumbai"
  },
  {
    "key": "commons-49",
    "file": "File:Girgaum Chowpatty Beach.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Girgaon Chowpatty Mumbai"
  },
  {
    "key": "commons-50",
    "file": "File:Chowpatti Beach (Girgaum Chowpatty).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Girgaon Chowpatty Mumbai"
  },
  {
    "key": "commons-51",
    "file": "File:KalaGhoda, Fort,Mumbai - panoramio (34).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Fort Kala Ghoda"
  },
  {
    "key": "commons-52",
    "file": "File:KalaGhoda, Fort,Mumbai - panoramio (78).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Fort Kala Ghoda"
  },
  {
    "key": "commons-53",
    "file": "File:Colaba Causeway, Bombay.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Colaba Causeway"
  },
  {
    "key": "commons-54",
    "file": "File:Mumbai - Kuvar House Building.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Colaba Causeway"
  },
  {
    "key": "commons-55",
    "file": "File:Marine Drive Mumbai (1).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Marine Drive Mumbai"
  },
  {
    "key": "commons-56",
    "file": "File:Marine Drive Mumbai (2).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Marine Drive Mumbai"
  },
  {
    "key": "commons-57",
    "file": "File:Mumbai, India, Bombay, Chowpatty (Chaupati) Beach.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Girgaon Chowpatty Mumbai"
  },
  {
    "key": "commons-58",
    "file": "File:Mumbai, India, Mumbai city skyline.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Girgaon Chowpatty Mumbai"
  },
  {
    "key": "commons-59",
    "file": "File:Bandra worli sealinkബാന്ദ്ര-വർളി കടൽപാലം.JPG",
    "credit": "Wikimedia Commons contributor",
    "query": "Bandra Mumbai"
  },
  {
    "key": "commons-60",
    "file": "File:Mumbai 03-2016 104 Bandra station.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Bandra Mumbai"
  },
  {
    "key": "commons-61",
    "file": "File:KalaGhoda, Fort,Mumbai - panoramio (18).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Fort Kala Ghoda"
  },
  {
    "key": "commons-62",
    "file": "File:Taj Mahal Hotel, Colaba, South Bombay, Mumbai.tif",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Colaba Causeway"
  },
  {
    "key": "commons-63",
    "file": "File:Mumbai, India, Chowpatty Beach.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Girgaon Chowpatty Mumbai"
  },
  {
    "key": "commons-64",
    "file": "File:Mumbai, India, Bombay, Mumbai skyline at sunset.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Girgaon Chowpatty Mumbai"
  },
  {
    "key": "commons-65",
    "file": "File:Mumbai 03-2016 105 Bandra station surroundings.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Bandra Mumbai"
  },
  {
    "key": "commons-66",
    "file": "File:Mumbai 03-2016 106 Bandra station surroundings.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Bandra Mumbai"
  },
  {
    "key": "commons-67",
    "file": "File:KalaGhoda, Fort,Mumbai - panoramio (105).jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Mumbai Fort Kala Ghoda"
  },
  {
    "key": "commons-68",
    "file": "File:Mumbai, India, Indian family on the beach, Chowpatty Beach.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Girgaon Chowpatty Mumbai"
  },
  {
    "key": "commons-69",
    "file": "File:Mumbai, India, Family on the beach.jpg",
    "credit": "Wikimedia Commons contributor",
    "query": "Girgaon Chowpatty Mumbai"
  }
];
