"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BookmarkSimple, Clock, MapPin } from "@phosphor-icons/react/dist/ssr";
import { BottomNav, StatusLabel } from "@/components/ui";
import { experienceSeed } from "@/lib/seed";
import { readSaved, writeSaved } from "@/lib/saved";

export default function SavedPage() {
  const [ids, setIds] = useState<string[]>([]);
  useEffect(() => { const sync = () => setIds(readSaved()); sync(); window.addEventListener("local-tourist-saved-change", sync); return () => window.removeEventListener("local-tourist-saved-change", sync); }, []);
  const places = useMemo(() => ids.map((id) => experienceSeed.find((place) => place.id === id)).filter((place): place is typeof experienceSeed[number] => Boolean(place)), [ids]);
  return <main id="main-content" className="min-h-screen bg-canvas"><div className="mx-auto min-h-screen max-w-[1180px] bg-white lg:my-5 lg:min-h-[calc(100vh-40px)] lg:rounded-[28px] lg:shadow-card"><header className="flex items-center justify-between border-b border-line px-5 py-4 sm:px-8"><a href="/" className="flex items-center gap-2 text-sm font-bold"><ArrowLeft size={18} /> Home</a><h1 className="text-lg font-bold">Saved</h1><a href="/explore" className="text-sm font-bold text-blue">Explore</a></header><section className="px-5 pb-28 pt-10 sm:px-8 lg:px-14 lg:pb-14"><p className="text-xs font-bold uppercase tracking-[0.14em] text-blue">Your shortlist</p><h2 className="mt-3 text-4xl font-bold tracking-[-0.05em]">Places to revisit.</h2><p className="mt-4 max-w-xl leading-7 text-muted">Saved locally on this device for now. Availability and demo data may change before you visit.</p>{places.length ? <div className="mt-8 grid gap-4 sm:grid-cols-2">{places.map((place) => <article key={place.id} className="border border-line p-5"><div className="flex items-start justify-between"><StatusLabel tone={place.statusTone}>{place.status}</StatusLabel><button onClick={() => writeSaved(ids.filter((id) => id !== place.id))} aria-label={`Remove ${place.name}`} className="text-blue"><BookmarkSimple size={20} weight="fill" /></button></div><h3 className="mt-5 text-xl font-bold">{place.name}</h3><p className="mt-2 text-sm text-muted">{place.area} · {place.category}</p><div className="mt-4 flex flex-wrap gap-4 text-xs font-semibold text-muted"><span><Clock size={14} className="mr-1 inline" />{place.duration}</span><span><MapPin size={14} className="mr-1 inline" />{place.station}</span><span>{place.updated}</span></div><a href={`/experience/${place.id}`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-blue">View details <ArrowRight size={16} /></a></article>)}</div> : <div className="mt-8 border border-line bg-canvas p-8"><BookmarkSimple size={27} className="text-blue" /><h3 className="mt-5 text-xl font-bold">Nothing saved yet</h3><p className="mt-2 max-w-lg leading-7 text-muted">Save places from their detail pages to build a shortlist before you plan.</p><a href="/explore" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-blue px-4 py-3 text-sm font-bold text-white">Explore places <ArrowRight size={17} /></a></div>}</section><BottomNav /></div></main>;
}
