export type Experience = {
  id: string;
  name: string;
  area: string;
  city: "Mumbai" | "Navi Mumbai";
  zone: string;
  category: string;
  price: string;
  duration: string;
  travelTime: string;
  station: string;
  status: string;
  statusTone: "blue" | "green" | "amber";
  updated: string;
  description: string;
  mediaTitle: string;
  coordinates: [number, number];
  source: string;
  sourceUrl: string;
  confidence: string;
  lastChecked: string;
};

const demoSource = (id: string) => `https://example.com/sources/${id}`;

export const experienceSeed: Experience[] = [
  { id: "kala-ghoda-art-walk", name: "Kala Ghoda Art Walk", area: "Fort", city: "Mumbai", zone: "Fort / Kala Ghoda", category: "Culture", price: "₹700", duration: "2 hours", travelTime: "12 min", station: "Churchgate", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "A compact walk through galleries, public art, and heritage streets in the Fort district.", mediaTitle: "Local video awaiting verification", coordinates: [72.8311, 18.9275], source: "Curated demo record", sourceUrl: demoSource("kala-ghoda-art-walk"), confidence: "Demo data, not live", lastChecked: "2026-08-28" },
  { id: "sassoon-library-reading-hour", name: "David Sassoon Library Reading Hour", area: "Fort", city: "Mumbai", zone: "Fort / Kala Ghoda", category: "Culture", price: "₹300", duration: "90 min", travelTime: "10 min", station: "Churchgate", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "A quiet hour in a working heritage library hall a short walk from the Kala Ghoda precinct.", mediaTitle: "Local video awaiting verification", coordinates: [72.8326, 18.9244], source: "Curated demo record", sourceUrl: demoSource("sassoon-library-reading-hour"), confidence: "Demo data, not live", lastChecked: "2026-08-28" },
  { id: "fort-bakery-lanes", name: "Fort Bakery Lanes", area: "Fort", city: "Mumbai", zone: "Fort / Kala Ghoda", category: "Food", price: "₹450", duration: "75 min", travelTime: "14 min", station: "CSMT", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "Irani café snacks and bakery counters around the old Fort business streets.", mediaTitle: "Local video awaiting verification", coordinates: [72.8354, 18.9342], source: "Provider submission (demo)", sourceUrl: demoSource("fort-bakery-lanes"), confidence: "Awaiting confirmation", lastChecked: "2026-08-20" },
  { id: "marine-drive-sunset-walk", name: "Marine Drive Sunset Walk", area: "Marine Drive", city: "Mumbai", zone: "Marine Drive / Girgaon", category: "Nature", price: "Free", duration: "60 min", travelTime: "11 min", station: "Charni Road", status: "Verified demo record", statusTone: "green", updated: "Demo data", description: "A seafront promenade walk timed to the evening light on the Queens Necklace curve.", mediaTitle: "Local video awaiting verification", coordinates: [72.8216, 18.944], source: "Curated demo record", sourceUrl: demoSource("marine-drive-sunset-walk"), confidence: "Verified demo record", lastChecked: "2026-09-02" },
  { id: "girgaon-chowpatty-snack-trail", name: "Girgaon Chowpatty Snack Trail", area: "Girgaon", city: "Mumbai", zone: "Marine Drive / Girgaon", category: "Food", price: "₹350", duration: "90 min", travelTime: "13 min", station: "Charni Road", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "Beach-side stalls and long-running snack counters around Girgaon Chowpatty.", mediaTitle: "Local video awaiting verification", coordinates: [72.8103, 18.9522], source: "Resident recommendation (demo)", sourceUrl: demoSource("girgaon-chowpatty-snack-trail"), confidence: "Community reported", lastChecked: "2026-08-14" },
  { id: "bandra-village-chapel-loop", name: "Bandra Village Chapel Loop", area: "Bandra", city: "Mumbai", zone: "Bandra", category: "Culture", price: "₹400", duration: "2 hours", travelTime: "22 min", station: "Bandra", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "East Indian village lanes, small chapels, and heritage houses in Bandra West.", mediaTitle: "Local video awaiting verification", coordinates: [72.8298, 19.0585], source: "Curated demo record", sourceUrl: demoSource("bandra-village-chapel-loop"), confidence: "Demo data, not live", lastChecked: "2026-07-30" },
  { id: "hill-road-cafe-crawl", name: "Hill Road Café Crawl", area: "Bandra", city: "Mumbai", zone: "Bandra", category: "Food", price: "₹900", duration: "2 hours", travelTime: "20 min", station: "Bandra", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "A short crawl of independent cafés and bakeries along Hill Road.", mediaTitle: "Local video awaiting verification", coordinates: [72.8322, 19.0632], source: "Provider submission (demo)", sourceUrl: demoSource("hill-road-cafe-crawl"), confidence: "Awaiting confirmation", lastChecked: "2026-08-25" },
  { id: "bandra-street-art-walk", name: "Bandra Street Art Walk", area: "Bandra", city: "Mumbai", zone: "Bandra", category: "Culture", price: "₹550", duration: "90 min", travelTime: "21 min", station: "Bandra", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "Murals and compound-wall art through the fishing-village streets of Bandra West.", mediaTitle: "Local video awaiting verification", coordinates: [72.8411, 19.0606], source: "Resident recommendation (demo)", sourceUrl: demoSource("bandra-street-art-walk"), confidence: "Community reported", lastChecked: "2026-08-05" },
  { id: "juhu-beach-morning-walk", name: "Juhu Beach Morning Walk", area: "Juhu", city: "Mumbai", zone: "Juhu", category: "Nature", price: "Free", duration: "75 min", travelTime: "35 min", station: "Vile Parle", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "An early-morning shoreline walk before the crowds arrive at Juhu beach.", mediaTitle: "Local video awaiting verification", coordinates: [72.8265, 19.099], source: "Curated demo record", sourceUrl: demoSource("juhu-beach-morning-walk"), confidence: "Demo data, not live", lastChecked: "2026-07-22" },
  { id: "juhu-food-street-evening", name: "Juhu Food Street Evening", area: "Juhu", city: "Mumbai", zone: "Juhu", category: "Food", price: "₹650", duration: "2 hours", travelTime: "33 min", station: "Andheri", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "Evening chaat and street-food counters along the Juhu beach access lanes.", mediaTitle: "Local video awaiting verification", coordinates: [72.829, 19.1035], source: "Curated demo record", sourceUrl: demoSource("juhu-food-street-evening"), confidence: "Demo data, not live", lastChecked: "2026-08-18" },
  { id: "versova-fishing-village-walk", name: "Versova Fishing Village Walk", area: "Andheri", city: "Mumbai", zone: "Andheri", category: "Culture", price: "₹500", duration: "2 hours", travelTime: "40 min", station: "Versova", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "A walk through the Versova koliwada fishing village and its harbour lanes.", mediaTitle: "Local video awaiting verification", coordinates: [72.8026, 19.1355], source: "Resident recommendation (demo)", sourceUrl: demoSource("versova-fishing-village-walk"), confidence: "Community reported", lastChecked: "2026-07-28" },
  { id: "lokhandwala-market-hours", name: "Lokhandwala Market Hours", area: "Andheri", city: "Mumbai", zone: "Andheri", category: "Shopping", price: "₹800", duration: "2 hours", travelTime: "38 min", station: "Andheri West", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "Independent boutiques and street retail around the Lokhandwala complex market.", mediaTitle: "Local video awaiting verification", coordinates: [72.8294, 19.1364], source: "Curated demo record", sourceUrl: demoSource("lokhandwala-market-hours"), confidence: "Demo data, not live", lastChecked: "2026-08-11" },
  { id: "powai-lakeside-loop", name: "Powai Lakeside Loop", area: "Powai", city: "Mumbai", zone: "Powai", category: "Nature", price: "Free", duration: "90 min", travelTime: "30 min", station: "Kanjurmarg", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "A paved loop along the Powai lake edge with garden sections and bird spots.", mediaTitle: "Local video awaiting verification", coordinates: [72.906, 19.1176], source: "Curated demo record", sourceUrl: demoSource("powai-lakeside-loop"), confidence: "Demo data, not live", lastChecked: "2026-08-30" },
  { id: "powai-pottery-basics", name: "Powai Pottery Basics", area: "Powai", city: "Mumbai", zone: "Powai", category: "Workshop", price: "₹1200", duration: "2.5 hours", travelTime: "28 min", station: "Kanjurmarg", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "A beginner wheel-throwing session at a small studio in Hiranandani Gardens.", mediaTitle: "Local video awaiting verification", coordinates: [72.9045, 19.117], source: "Provider submission (demo)", sourceUrl: demoSource("powai-pottery-basics"), confidence: "Awaiting confirmation", lastChecked: "2026-09-01" },
  { id: "aarey-colony-nature-trail", name: "Aarey Colony Nature Trail", area: "Aarey", city: "Mumbai", zone: "Aarey", category: "Nature", price: "Free", duration: "2.5 hours", travelTime: "42 min", station: "Goregaon", status: "Weather dependent", statusTone: "amber", updated: "Demo data", description: "A shaded trail through Aarey's green sections. Trails are unlit after sunset.", mediaTitle: "Local video awaiting verification", coordinates: [72.8725, 19.1515], source: "Resident recommendation (demo)", sourceUrl: demoSource("aarey-colony-nature-trail"), confidence: "Community reported", lastChecked: "2026-08-08" },
  { id: "aarey-dairy-heritage-visit", name: "Aarey Dairy Heritage Visit", area: "Aarey", city: "Mumbai", zone: "Aarey", category: "Culture", price: "₹450", duration: "2 hours", travelTime: "45 min", station: "Goregaon", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "The old dairy settlements and grazing meadows that gave Aarey its name.", mediaTitle: "Local video awaiting verification", coordinates: [72.8779, 19.1466], source: "Curated demo record", sourceUrl: demoSource("aarey-dairy-heritage-visit"), confidence: "Demo data, not live", lastChecked: "2026-07-19" },
  { id: "matunga-breakfast-trail", name: "Matunga Breakfast Trail", area: "Matunga", city: "Mumbai", zone: "Dadar / Matunga", category: "Food", price: "₹550", duration: "90 min", travelTime: "18 min", station: "Matunga Road", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "A vegetarian breakfast route built around long-running South Indian cafés and bakeries.", mediaTitle: "Local video awaiting verification", coordinates: [72.8467, 19.0271], source: "Curated demo record", sourceUrl: demoSource("matunga-breakfast-trail"), confidence: "Demo data, not live", lastChecked: "2026-08-29" },
  { id: "dadar-flower-market-morning", name: "Dadar Flower Market Morning", area: "Dadar", city: "Mumbai", zone: "Dadar / Matunga", category: "Shopping", price: "Free", duration: "75 min", travelTime: "20 min", station: "Dadar", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "The wholesale flower market at its busiest in the early morning hours.", mediaTitle: "Local video awaiting verification", coordinates: [72.842, 19.0185], source: "Resident recommendation (demo)", sourceUrl: demoSource("dadar-flower-market-morning"), confidence: "Community reported", lastChecked: "2026-08-22" },
  { id: "shivaji-park-heritage-loop", name: "Shivaji Park Heritage Loop", area: "Dadar", city: "Mumbai", zone: "Dadar / Matunga", category: "Culture", price: "Free", duration: "60 min", travelTime: "22 min", station: "Dadar", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "A ground-level loop around Shivaji Park with cricket history and neighbourhood landmarks.", mediaTitle: "Local video awaiting verification", coordinates: [72.8433, 19.031], source: "Curated demo record", sourceUrl: demoSource("shivaji-park-heritage-loop"), confidence: "Demo data, not live", lastChecked: "2026-08-16" },
  { id: "vashi-market-loop", name: "Vashi Market Loop", area: "Vashi", city: "Navi Mumbai", zone: "Vashi", category: "Shopping", price: "Free", duration: "75 min", travelTime: "9 min", station: "Vashi", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "A practical route through market lanes, local produce stalls, and everyday neighborhood shopping.", mediaTitle: "Local video awaiting verification", coordinates: [72.9986, 19.076], source: "Curated demo record", sourceUrl: demoSource("vashi-market-loop"), confidence: "Demo data, not live", lastChecked: "2026-08-27" },
  { id: "vashi-mini-seashore-walk", name: "Vashi Mini Seashore Walk", area: "Vashi", city: "Navi Mumbai", zone: "Vashi", category: "Nature", price: "Free", duration: "60 min", travelTime: "12 min", station: "Vashi", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "A short waterfront park walk with creek views near the Vashi seashore face.", mediaTitle: "Local video awaiting verification", coordinates: [72.995, 19.067], source: "Curated demo record", sourceUrl: demoSource("vashi-mini-seashore-walk"), confidence: "Demo data, not live", lastChecked: "2026-08-27" },
  { id: "seawoods-creek-boardwalk", name: "Seawoods Creek Boardwalk", area: "Nerul/Seawoods", city: "Navi Mumbai", zone: "Nerul / Seawoods", category: "Nature", price: "Free", duration: "90 min", travelTime: "25 min", station: "Seawoods", status: "Weather dependent", statusTone: "amber", updated: "Demo data", description: "A mangrove creek boardwalk best in dry weather. Sections close during heavy rain.", mediaTitle: "Local video awaiting verification", coordinates: [73.0152, 19.033], source: "Curated demo record", sourceUrl: demoSource("seawoods-creek-boardwalk"), confidence: "Demo data, not live", lastChecked: "2026-08-19" },
  { id: "nerul-station-food-lanes", name: "Nerul Station Food Lanes", area: "Nerul/Seawoods", city: "Navi Mumbai", zone: "Nerul / Seawoods", category: "Food", price: "₹400", duration: "75 min", travelTime: "24 min", station: "Nerul", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "Evening food stalls and mess-style eateries around Nerul station east.", mediaTitle: "Local video awaiting verification", coordinates: [73.0158, 19.0446], source: "Provider submission (demo)", sourceUrl: demoSource("nerul-station-food-lanes"), confidence: "Awaiting confirmation", lastChecked: "2026-09-03" },
  { id: "belapur-mango-grove-walk", name: "Belapur Mango Grove Walk", area: "Belapur", city: "Navi Mumbai", zone: "Belapur", category: "Nature", price: "Free", duration: "2 hours", travelTime: "28 min", station: "Belapur", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "An old mango grove and village edge walk under the Belapur hills.", mediaTitle: "Local video awaiting verification", coordinates: [73.0286, 19.015], source: "Resident recommendation (demo)", sourceUrl: demoSource("belapur-mango-grove-walk"), confidence: "Community reported", lastChecked: "2026-08-02" },
  { id: "belapur-artisan-market", name: "Belapur Artisan Market", area: "Belapur", city: "Navi Mumbai", zone: "Belapur", category: "Shopping", price: "₹300", duration: "90 min", travelTime: "26 min", station: "Belapur", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "Weekend artisan stalls with crafts and home goods near the CBD Belapur sector 15 pocket.", mediaTitle: "Local video awaiting verification", coordinates: [73.026, 19.0218], source: "Curated demo record", sourceUrl: demoSource("belapur-artisan-market"), confidence: "Demo data, not live", lastChecked: "2026-08-24" },
  { id: "kharghar-hills-view", name: "Kharghar Hills View", area: "Kharghar", city: "Navi Mumbai", zone: "Kharghar", category: "Nature", price: "Free", duration: "2.5 hours", travelTime: "24 min", station: "Kharghar", status: "Weather dependent", statusTone: "amber", updated: "Demo data", description: "A short nature outing with broad views across Navi Mumbai. Check conditions before starting.", mediaTitle: "Local video awaiting verification", coordinates: [73.0691, 19.0469], source: "Curated demo record", sourceUrl: demoSource("kharghar-hills-view"), confidence: "Demo data, not live", lastChecked: "2026-08-13" },
  { id: "kharghar-utsav-chowk-evening", name: "Kharghar Utsav Chowk Evening", area: "Kharghar", city: "Navi Mumbai", zone: "Kharghar", category: "Food", price: "₹350", duration: "75 min", travelTime: "22 min", station: "Kharghar", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "Evening snack counters around the Utsav Chowk junction promenade.", mediaTitle: "Local video awaiting verification", coordinates: [73.0667, 19.0366], source: "Curated demo record", sourceUrl: demoSource("kharghar-utsav-chowk-evening"), confidence: "Demo data, not live", lastChecked: "2026-08-21" },
  { id: "airoli-creek-flamingo-point", name: "Airoli Creek Flamingo Point", area: "Airoli", city: "Navi Mumbai", zone: "Airoli", category: "Nature", price: "Free", duration: "2 hours", travelTime: "30 min", station: "Airoli", status: "Weather dependent", statusTone: "amber", updated: "Demo data", description: "A seasonal creek-side watching point. Flamingo visits vary by month and tide.", mediaTitle: "Local video awaiting verification", coordinates: [72.9968, 19.155], source: "Resident recommendation (demo)", sourceUrl: demoSource("airoli-creek-flamingo-point"), confidence: "Community reported", lastChecked: "2026-07-15" },
  { id: "airoli-maker-space-basics", name: "Airoli Maker Space Basics", area: "Airoli", city: "Navi Mumbai", zone: "Airoli", category: "Workshop", price: "₹1000", duration: "2 hours", travelTime: "32 min", station: "Airoli", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "A guided introduction to hand tools and small builds at a community maker space.", mediaTitle: "Local video awaiting verification", coordinates: [73.0021, 19.1498], source: "Provider submission (demo)", sourceUrl: demoSource("airoli-maker-space-basics"), confidence: "Awaiting confirmation", lastChecked: "2026-08-31" },
  { id: "panvel-old-market-walk", name: "Panvel Old Market Walk", area: "Panvel", city: "Navi Mumbai", zone: "Panvel", category: "Shopping", price: "Free", duration: "90 min", travelTime: "45 min", station: "Panvel", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "The old Panvel market streets around the historic wada lanes and temple squares.", mediaTitle: "Local video awaiting verification", coordinates: [73.1107, 18.9894], source: "Curated demo record", sourceUrl: demoSource("panvel-old-market-walk"), confidence: "Demo data, not live", lastChecked: "2026-07-26" },
  { id: "panvel-lakeside-evening", name: "Panvel Lakeside Evening", area: "Panvel", city: "Navi Mumbai", zone: "Panvel", category: "Nature", price: "Free", duration: "60 min", travelTime: "43 min", station: "Panvel", status: "Demo seed record", statusTone: "blue", updated: "Demo data", description: "A calm evening lakefront walk popular with local families in Panvel.", mediaTitle: "Local video awaiting verification", coordinates: [73.101, 18.996], source: "Resident recommendation (demo)", sourceUrl: demoSource("panvel-lakeside-evening"), confidence: "Community reported", lastChecked: "2026-08-09" },
];

export const zones = Array.from(new Set(experienceSeed.map((experience) => experience.zone)));

export type EventSeed = {
  id: string;
  name: string;
  venue: string;
  distance: string;
  timeLabel: string;
  price: string;
  category: string;
  confidence: string;
  updated: string;
  source: string;
  startMinutes: number;
  endMinutes: number;
  travelMinutes: number;
  previousVenue?: string;
  previousStartMinutes?: number;
  previousPrice?: string;
};

export const eventSeed: EventSeed[] = [
  { id: "fort-open-studios", name: "Fort Open Studios", venue: "Multiple venues in Fort", distance: "18 min away", timeLabel: "Starts 6:30 PM", price: "Free entry", category: "Art", confidence: "Demo data, not live", updated: "Needs verification", source: "Curated demo record", startMinutes: 30, endMinutes: 240, travelMinutes: 18 },
  { id: "seawoods-makers-market", name: "Seawoods Makers Market", venue: "Seawoods, Navi Mumbai", distance: "32 min away", timeLabel: "This weekend", price: "₹50 entry", previousPrice: "Free entry", category: "Market", confidence: "Demo data, not live", updated: "Needs verification", source: "Curated demo record", startMinutes: 480, endMinutes: 900, travelMinutes: 32 },
  { id: "bandra-small-stage", name: "Small Stage: Local Stories", venue: "Bandra West", previousVenue: "Bandra West community hall", previousStartMinutes: 150, distance: "26 min away", timeLabel: "Starts 8:00 PM", price: "From ₹400", category: "Performance", confidence: "Community reported", updated: "Needs confirmation", source: "Public event submission", startMinutes: 90, endMinutes: 330, travelMinutes: 26 },
];

export type MediaSeed = {
  id: string;
  experienceId: string;
  platform: "youtube" | "instagram";
  url: string;
  title: string;
  creator: string;
  mediaType: "Video" | "Reel";
  publishedAt: string;
  state: "Approved" | "Needs review" | "Archived";
  note: string;
};

export const mediaSeed: MediaSeed[] = [
  { id: "media-kala-ghoda", experienceId: "kala-ghoda-art-walk", platform: "youtube", url: "https://www.youtube.com/watch?v=aqz-KE-bpKQ", title: "Galleries and street art around Kala Ghoda", creator: "Fort heritage walks", mediaType: "Video", publishedAt: "Older video", state: "Approved", note: "Demo seed record. Confirm the source shows this place before presenting it." },
  { id: "media-matunga", experienceId: "matunga-breakfast-trail", platform: "youtube", url: "https://youtu.be/9bZkp7q19f0", title: "South Indian breakfast institutions of Matunga", creator: "Mumbai food trails", mediaType: "Video", publishedAt: "This year", state: "Approved", note: "Demo seed record. Confirm the source shows this place before presenting it." },
  { id: "media-vashi", experienceId: "vashi-market-loop", platform: "instagram", url: "https://www.instagram.com/reel/demo-market-reel/", title: "Market lanes at closing hour", creator: "Navi Mumbai daily", mediaType: "Reel", publishedAt: "Recent", state: "Approved", note: "Embed not permitted for this source. Open the platform link instead." },
  { id: "media-kharghar", experienceId: "kharghar-hills-view", platform: "youtube", url: "https://www.youtube.com/watch?v=aqz-KE-bpKQ", title: "Hilltop views after monsoon", creator: "Unverified upload", mediaType: "Video", publishedAt: "Unknown", state: "Archived", note: "Removed from discovery after the source failed verification. Demo placeholder video; confirm the source shows this place before any approval." },
];
