/**
 * Geocode generated place names to exact OSM coordinates.
 *
 * For every place tuple (name + area) the script queries Nominatim with a
 * bounded viewbox around the area anchor, then accepts a candidate only when
 * BOTH hold:
 *   1. it sits within MAX_KM of the area anchor, and
 *   2. it shares at least one significant name token with the place.
 *
 * Accepted matches are written to lib/data/geocoded.generated.ts with their
 * real coordinates; misses are simply absent (the factory keeps the honest
 * area-anchor jitter for those and labels confidence accordingly).
 *
 * Usage:
 *   npx tsx scripts/geocode-places.ts             # resume from saved progress
 *   npx tsx scripts/geocode-places.ts --report    # coverage stats only
 *
 * Nominatim policy: max 1 request/second with a descriptive user agent.
 */
import fs from "node:fs";
import path from "node:path";
import { zoneRows } from "../lib/data/zones";
import { foodNames } from "../lib/data/places/food";
import { nightlifeNames } from "../lib/data/places/nightlife";
import { shoppingNames } from "../lib/data/places/shopping";
import { adventureNames } from "../lib/data/places/adventure";
import { recreationNames } from "../lib/data/places/recreation";
import { stayNames } from "../lib/data/places/stay";
import { cultureNames } from "../lib/data/places/culture";
import { natureNames } from "../lib/data/places/nature";
import { workshopNames } from "../lib/data/places/workshop";
import { familyNames } from "../lib/data/places/family";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT_FILE = path.join(ROOT, "lib", "data", "geocoded.generated.ts");
const UA = "Ananta-demo-dataset/1.0 (geocoding demo places via Nominatim; one-off batch)";
const MAX_KM = 3.5;
const VIEWBOX_PAD_LNG = 0.07;
const VIEWBOX_PAD_LAT = 0.06;
const RPS_DELAY_MS = 1100;

const slug = (value: string) =>
  value
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const NAMES_BY_CATEGORY: Record<string, Record<string, string[]>> = {
  Food: foodNames, Nightlife: nightlifeNames, Shopping: shoppingNames, Adventure: adventureNames,
  Recreation: recreationNames, Stay: stayNames, Culture: cultureNames, Nature: natureNames,
  Workshop: workshopNames, Family: familyNames,
};

const VALID_AREAS = new Set(zoneRows.map((zone) => zone.area));
const ZONE_BY_AREA = new Map(zoneRows.map((zone) => [zone.area, zone]));

type Task = { id: string; name: string; area: string };

/** Every generated place tuple that maps to a real zone area. */
function allTasks(): Task[] {
  const tasks: Task[] = [];
  for (const namesByArea of Object.values(NAMES_BY_CATEGORY)) {
    for (const [area, names] of Object.entries(namesByArea)) {
      if (!VALID_AREAS.has(area)) continue;
      for (const name of names) tasks.push({ id: slug(name), name, area });
    }
  }
  return tasks;
}

type Row = { id: string; coordinates: [number, number]; match: string };

function readSaved(): Map<string, Row> {
  if (!fs.existsSync(OUT_FILE)) return new Map();
  const source = fs.readFileSync(OUT_FILE, "utf8");
  const start = source.indexOf("= [");
  const end = source.lastIndexOf("];");
  try {
    const rows: Row[] = JSON.parse(source.slice(start + 2, end + 1));
    return new Map(rows.map((row) => [row.id, row]));
  } catch {
    return new Map();
  }
}

function writeSaved(rows: Map<string, Row>) {
  const body =
    "// Generated by scripts/geocode-places.ts - do not edit by hand.\n" +
    "// Every coordinate was matched against OpenStreetMap via Nominatim and\n" +
    "// validated against its area anchor. Missing ids fall back to the\n" +
    "// area-anchor pin with an honest demo-estimate confidence label.\n" +
    "export type GeocodedPlace = { id: string; coordinates: [number, number]; match: string };\n\n" +
    "export const geocodedPlaces: GeocodedPlace[] = " + JSON.stringify(Array.from(rows.values()), null, 2) + ";\n";
  fs.writeFileSync(OUT_FILE, body);
}

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

async function nominatim(query: string, viewbox: string): Promise<{ lat: number; lon: number; display_name: string }[]> {
  const url =
    "https://nominatim.openstreetmap.org/search?format=jsonv2&limit=3&bounded=1" +
    "&viewbox=" + viewbox +
    "&q=" + encodeURIComponent(query);
  try {
    const response = await fetch(url, { headers: { "user-agent": UA } });
    if (!response.ok) return [];
    const data = await response.json();
    return Array.isArray(data) ? data : [];
  } catch {
    return [];
  }
}

function distanceKm(a: [number, number], b: [number, number]): number {
  const dLng = (a[0] - b[0]) * 111.32 * Math.cos(((a[1] + b[1]) / 2) * (Math.PI / 180));
  const dLat = (a[1] - b[1]) * 110.57;
  return Math.sqrt(dLng * dLng + dLat * dLat);
}

const SIGNIFICANT = (token: string) => token.length >= 4 && !["mumbai", "navi"].includes(token);

/** Trailing experience modifiers that are not part of a venue's name. */
const MODIFIERS = [
  "morning", "afternoon", "evening", "night", "sunrise", "sunset", "monsoon",
  "weekend", "slot", "experience", "outing", "session", "visit", "trip", "tour",
  "walk", "stroll", "hike", "trek", "run", "ride", "drive", "browsing", "hop",
];

function queryVariants(name: string): string[] {
  const words = name.split(/\s+/);
  const variants = [name];
  let trimmed = [...words];
  for (let i = 0; i < 3 && trimmed.length > 1; i += 1) {
    const last = trimmed[trimmed.length - 1].toLowerCase().replace(/[^a-z]/g, "");
    if (!MODIFIERS.includes(last)) break;
    trimmed = trimmed.slice(0, -1);
    if (trimmed.length) variants.push(trimmed.join(" "));
  }
  return Array.from(new Set(variants));
}

async function geocodeTask(task: Task): Promise<Row | null> {
  const zone = ZONE_BY_AREA.get(task.area);
  if (!zone) return null;
  const anchor = zone.coordinates;
  const viewbox = [
    anchor[0] - VIEWBOX_PAD_LNG, anchor[1] + VIEWBOX_PAD_LAT,
    anchor[0] + VIEWBOX_PAD_LNG, anchor[1] - VIEWBOX_PAD_LAT,
  ].map((n) => n.toFixed(4)).join(",");
  const city = zone.city === "Navi Mumbai" ? "Navi Mumbai" : "Mumbai";
  const placeTokens = new Set(
    task.name.toLowerCase().split(/[^a-z0-9]+/).filter(SIGNIFICANT),
  );
  const placeTokenList = Array.from(placeTokens);

  // Bounded simple queries work best; a city suffix is the fallback when the
  // bare variant returns nothing (e.g. "Kharghar hills" vs "... Navi Mumbai").
  const queries: string[] = [];
  for (const variant of queryVariants(task.name)) {
    queries.push(variant);
    queries.push(variant + " " + city);
  }
  for (const query of queries) {
    const results = await nominatim(query, viewbox);
    await sleep(RPS_DELAY_MS);
    for (const result of results) {
      const coords: [number, number] = [Number(result.lon), Number(result.lat)];
      if (distanceKm(anchor, coords) > MAX_KM) continue;
      const resultTokens = result.display_name.toLowerCase().split(/[^a-z0-9]+/);
      const overlap = placeTokenList.some((token) => resultTokens.includes(token));
      if (!overlap) continue;
      return { id: task.id, coordinates: coords, match: result.display_name.split(",").slice(0, 2).join(",") };
    }
  }
  return null;
}

async function main() {
  const args = process.argv.slice(2);
  const tasks = allTasks();
  const saved = readSaved();

  if (args.includes("--report")) {
    console.log("tasks: " + tasks.length + ", geocoded: " + saved.size + " (" + Math.round((saved.size / tasks.length) * 100) + "%)");
    return;
  }

  const pending = tasks.filter((task) => !saved.has(task.id));
  const onlyArg = args.find((arg) => arg.startsWith("--only="));
  const onlyAreas = onlyArg ? onlyArg.slice(7).split(",") : null;
  const queue = onlyAreas ? pending.filter((task) => onlyAreas.includes(task.area)) : pending;
  const limitArg = args.find((arg) => arg.startsWith("--limit="));
  const limit = limitArg ? Number(limitArg.slice(8)) : queue.length;
  const batch = queue.slice(0, limit);
  console.log("tasks: " + tasks.length + " | saved: " + saved.size + " | pending: " + pending.length + (onlyAreas ? " | pilot areas: " + onlyAreas.join(",") : "") + " | batch: " + batch.length);

  let found = 0;
  for (let index = 0; index < batch.length; index += 1) {
    const task = batch[index];
    const row = await geocodeTask(task);
    if (row) {
      saved.set(task.id, row);
      found += 1;
      console.log("ok  " + task.id + " -> " + row.match + " [" + row.coordinates.join(",") + "]");
    }
    if (index % 20 === 19 || index === batch.length - 1) {
      writeSaved(saved);
      console.log("-- progress: " + (saved.size) + "/" + tasks.length + " saved");
    }
  }
  writeSaved(saved);
  console.log("done. new matches: " + found + ", total: " + saved.size + "/" + tasks.length);
}

main();
